server.py

Here's a fix for GH-243
This was a regression from GH-226. Basically I should have tested the case where the asset is uploaded. That's what the decode('utf-8') was for originally.
When an asset is upload, it gets uploaded as multipart/form-data. The form metadata for the asset gets posted as individual params instead of in one JSON encoded string via a param named model.
Since the data is not in JSON encoded string format, we skip the JSON decoding that converts the form data to unicode automatically.
This means we have to decode to utf-8 in this case. Here I make the assumption that utf-8 will always be the encoding if using Screenly's admin interface.
I did spend quite a bit of time trying to figure how to pass "Accept-Charset" using jQuery File upload, but it never added the header. …

GH-243 Fix unicode bug

---

LICENSE

I'm not much into legal stuff, so not sure if it's done right, but I've had a bit of trouble finding the license for this project, with most obvious location (LICENSE or COPYING file in the project dir) being sadly absent.
Currently it seem to be only mentioned in the docs on [screenlyapp.com](https://www.screenlyapp.com/ose/#licensing) and vewer.py / server.py headers.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/330)

Add license file (GPL-2.0 + commercial)

---

views/index.haml
views/settings.haml
views/system_info.haml

i think its a better way to open "external" links - like the Wireload Link in the footer.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/343)

Open Extern Links in new Tab

---

ansible/roles/system/tasks/main.yml
bin/install.sh

Using a swapfile on an SD card is a sure way of trashing it and dramatically shorten the life span. It's much better to kill the `oom-killer` kill processes than the SD card wearing out.

Disable swap

---

ansible/roles/system/tasks/main.yml

Sometimes Wheezy acts up and we need to install this package and then reboot.

Wheezy fix

---

ansible/roles/screenly/tasks/main.yml
ansible/roles/system/tasks/main.yml

* Disables touchscreen
* Minor formatting fixes of messages
* Adds cleanup when running with system upgrade
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/401)

Touchpad fix

---

server.py
settings.py

Addresses #333 - 24 hr clock setting not applied
Add CONFIGURABLE_SETTINGS dict to settings file and
iterate when saving settings from UI
UI settings include use_24_hour_clock setting, but only the
DEFAULTS['viewer'] dict were being checked, resulting in the time
preference not being persisted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/365)

Save 24 clock setting when amended in UI

---

Dockerfile
server.py

Bumps up timeout to 240s. This isn't a proper fix to large uploads, but rather a bandaid. A proper fix would be to chunk the uploads to mitigate the timeout issue entirely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/405)

Fixes Gunicorn timeout

---

lib/utils.py
requirements.txt
server.py
static/js/screenly-ose.coffee
static/js/screenly-ose.js

Use moment for crossbrowser convert utc to localtime. Spec for Date.parse (new Date) requires timezone. Server does not knows about timezones. We need to add 'Z' to provided by server string instead some browsers( IE and FF) will think that it is localtime
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/318)

fix asset time change after update

---

lib/utils.py

Solves issue with certain Web Application Firewalls (WAF) that blocks the user agent from [Python Requests](http://docs.python-requests.org/en/master/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/417)

Refs #413. Override user agent for requests to match uzbl.

---

Dockerfile
requirements.txt

Next attempt. Current version of cffi is 1.7.0 in both Docker container and Pi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/465)

Ensure the Dockerfile works with current version of PIP

---

bin/run_upgrade.sh

--proto '=https' forces curl to only use https:// which will prevent another http:// redirect mistake from occurring anywhere in the chain
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/482)

Update URL to new domain, force HTTPS only

---

bin/install.sh

GitHub does a 301 from http:// to https:// - we can avoid the redirect and interception risk if https:// is used directly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/483)

Use https:// for GitHub repo

---

.travis.yml
static/spec/jasmine/phantom-console-reporter.js
static/spec/runner.sh

use GNU timeout (7 sec) for handle phantomjs hangs, retry 10 times

fix integration tests

---

viewer.py

Added exception handling during video playback, as unforeseen situations are possible. 
For example, on the hosting with video the limit of requests is established. In this case, sometimes the following happens: asset is passed check in url_fails function, but when trying to play the video the request is rejected, which causes viewer to crash.

exception handling

---

ansible/roles/network/files/screenly_net_mgr.py

As the default `ConfigParser` does interpolation with the `%` character, WiFi password etc. with this character won't work. This ensures these fields are parsed as-is.

Add support for WiFi passwords with the '%' character

---

ansible/roles/screenly/tasks/main.yml
ansible/site.yml

It is necessary that websocket_server_layer starts after installing Screenly

Restart websocket layer

---

server.py
static/js/screenly-ose.coffee
static/js/screenly-ose.js
templates/index.html
viewer.py

Added front-end buttons for next-prev. 
In addition, before https://github.com/Screenly/screenly-ose/commit/0f3df0d80d727c4bc79e54a182d1dd6d57c31057, we often received an incorrect `video` duration ('N/A'). after this, when trying to edit such `videos`, we are getting an error. now it is fixed.
Refs #638

Next previous buttons

---

ansible/roles/network/files/screenly_net_mgr.py
lib/utils.py

In USB gadget mode, the network interface shows up as usb0.  You might want to use this interface for a Pi Zero running signage near another machine that can provide network connectivity via USB.

Add support for usb0 device

---

viewer.py

Apparently, this arose if we pressed back before the `scheduler` was created. for example, while the `splash_page` on the screen. in addition there was a problem if we click on any navigation buttons quickly several times. it was only on Resin
Refs #700

Fix viewer for Resin

---

README.md

I wasn't able to run the docker image, and found that the docker wasn't listening to connections from my computer, this is a quick hack for it to work.

docs: By default, listen on all (more reasonable default for new users)

---

ansible/roles/system/files/10-serverflags.conf
ansible/roles/system/tasks/main.yml

Sometimes disabling DPMS does not work. If you apply these settings, the screen will not darken, even if DPMS is enabled.
Refs #703

Fix black screen

---

lib/github.py
tests/updates_test.py
viewer.py

The `viewer` breaks down when trying to check for updates without an internet connection. Here it's prevented.
Refs #741

Fix for check_update

---

viewer.py

addition for https://github.com/Screenly/screenly-ose/pull/742.
I tested 742 on my machine (for more convenient debugging), but for some reason AttributeError (`six` module) arises on Pi.
Refs #740 #744

Fix for Viewer

---

ansible/roles/screenly/files/screenly.conf
settings.py
templates/settings.html
viewer.py

Added "Enable offline mode" item.
By default if there is no connection, it will be offered to select wifi network (using resin wifi), but if this option is enabled, assets will just start to be displayed.
Refs #764

Enable offline mode

---

settings.py

I ran into an issue where my config file wasn't where it was expected. As it was, Screenly-OSE simply crashed with exit(1) rather than just using the defaults. This PR will fix that issue by loading the defaults and saving the configuration file.

Use defaults if config file missing.

---

settings.py

Previous changes I created instituted hashing the password that is stored. However, I found that if the user had already typed in a password and then tried to login, they could never succeed (because what was entered during authentication was hashed before being checked). This corrects that by checking the stored password length and seeing if it is less than 64 (a hashed password length) and if it is it assumes that it needs hashed. Fixes the issue created with #828

Fix issue created by hashing password

---

lib/utils.py

Ran into an issue uploading a movie file created in iMovie. The file had issues decoding unicode stored in the video's metadata. This patch fixes the issue by making it ignore the decoding errors. I only run on a raspberry pi, so I am not sure if the same issue would exist with ffprobe, so I did not include the fix on line 97 as well.

Fix issue with unicode metadata on uploaded video.

---

ansible/roles/system/tasks/main.yml

Since ansible 2.1 this parameter is available.
https://docs.ansible.com/ansible/latest/modules/apt_module.html

Use autoremove parameter from ansible instead of command.

---

ansible/roles/screenly/tasks/main.yml

I do not know why this problem arose, I did not change the code to run the containers (this worked several weeks ago).
anyway at the moment the containers are created and are in the "stop" state, they don't start after reboot.
after this PR, systemd services will stop during an update, the containers will be started immediately after pulling.

Fixed: containers don't start after experimental update

---

html_templates.py
server.py
settings.py
tests/server_test.py
tests/viewer_test.py

I had to fix a problem with a screenly install yesterday.  The emacs on the rpi complained about the "utf8" coding, but "utf-8" seems to work well.

hyphenate utf8 for older emacs on jessie

---

lib/utils.py

Change get_node_ip to also work with ipv6-only setups.
Without this, if a pi does not have an ipv4 connection, get_node_ip will fail.

Make ipv6-only setups work

---

.travis.yml
README.md
static/spec/phantom-runner.js

It looks like the spec runner is using server.py and working well.  I don't think that using the simpleHTTPserver is needed.  On the chance that it is actually needed, we can use :8081 in the ```.travis.yml``` and ```phantomjs-runner.js``` files.

Is simple http server needed

---

ansible/roles/screenly/files/plymouth-quit-wait.service
ansible/roles/screenly/files/plymouth-quit.service
ansible/roles/screenly/tasks/main.yml

This fixes for #836 issue.
We have black screen because the splashscreen stop before the launch of all services .
These changes stay plymouth service until the boot is fully loaded and the screenly-viewer is launched.

Fixes black_screen when boot the system

---

ansible/roles/screenly/files/uzbl-config
viewer.py

This fixes for #848 issue.
If screenly viewer has a web page asset with an alert, confirmation or promt, the viewer will stuck until we close the interactive box.
These fixes allow you to insert a js code that overwrite alerts, confirms and prompts in most cases, through the event in the config file uzbl. However, there is a little chance that this will not help, and then we catch the event when the browser focus has losted, and at the end of the asset's duration we close the page.

Some fixes for stuck when alert, confirm or prompt

---

server.py
static/js/screenly-ose.coffee
static/js/screenly-ose.js

I was able to reproduce this issue #841.
The reason is the incorrect definition of the file mimetype in js code.
This edits allows to take the default value, if js could not determine the type of file.
Also i have this error when upload file without file extension.
For this situation i made edits in server python file.

Bug associated with determining the type of file

---

static/js/screenly-ose.coffee
static/js/screenly-ose.js

I was able to reproduce this issue #841.
The reason is the incorrect definition of the file mimetype in js code.
This edits allows to take the default value, if js could not determine the type of file.

Bug associated with determining the type of file for experimental

---

ansible/roles/splashscreen/files/plymouthd.default
ansible/roles/splashscreen/tasks/main.yml

#922
When I was solving the issue described here #836, I was faced with the fact that on some versions of Raspberry Pi( In my case, Raspberry Pi 1 and sometimes with Raspberry Pi Zero W) there haven't Screenly splashscreen. Instead, I had a splashscreen with 3 dots is displayed.
These edits fix this problem.

Fixes for splashscreen

---

templates/hotspot.html

Undefined url_for in hotspot, when starting script start_resin_wifi.

Remove url_for from hotspot.html

---

ansible/roles/screenly/tasks/main.yml

When performing a task with creating a screely-ose-viewer container in during the work of the ansible-playbook(experimental branch). the container starts up immediately. It blocks the work of the ansible-playbook. (screenly-viewer running with splash page and also we can't use keyboard) 
These changes pause working of this container until the system is rebooted.
In official ansible documentation we can read about paused tag for docker_container, but this tag not worked there.
If changes state in task, It also does not give the desired result. Since it will be necessary to create services for running containers with system.
Steps to reproduce this issue, eg:
* Run ansible-playbook in experimental branch
* Wait create screenly-viewer task

Add pause for screenly-viewer container in ansible-playbook

---

Dockerfile.template
Dockerfile.viewer

#806
Updated version of screenly-webview from 0.1 to v0.2
https://github.com/Screenly/screenly-ose-webview/releases/tag/0.2

Updated version of screenly-webview to v0.2

---

lib/assets_helper.py
lib/queries.py

The problem is described here #973 
I was able to reproduce it.
I've added more than 200 assets and this has had a huge impact on performance.
The problem was the ` save_ordering() ` function.
With such a volume of assets, the speed of execution this function ranged from 5-20(!) seconds, which caused the "database is locked" error.
After my edits, the execution speed of the function is about 0.1 seconds.

Optimize save ordering

---

viewer.py

Refs: #974 #966
These edits resolved problem when page load was fail.

No longer stops viewer if page load failed

---

ansible/roles/nginx/files/nginx.conf
static/js/settings.coffee
static/js/settings.js

Discussion of the issue #977
These edits make fix when it was not possible to download a backup if .tar is generated more than 30 seconds.
Now the timeout is 30 minutes.

Set large timeout for backup

---

Dockerfile.worker
ansible/roles/screenly/files/screenly-celery.service
server.py

These edits do not allow to run more than one screenly_upgrade task from the web interface.

Only one active upgrade_screenly task

---

lib/errors.py
viewer.py

Thanks to this issue #995, I found next problem
Reproduce steps:
- Activate asset with this url https://www.instagram.com/epsbn9/?hl=en
- Disable asset above
- Try activate asset above one more time.
- Then we'll see that we're stuck on black_page.html
These edits have:
Send a signal SIGALRM in 10 seconds when we started to receive data from the browser process. If the browser process does not receive any data during this time, an exception will be thrown out and the viewer will continue to work.

SIGALRM when viewer stuck

---

Dockerfile.template

These steps were necessary in order to get screenly to function correctly when installing it on Balena Cloud. I've decided to PR these changes in an attempt to share my fixes with everyone else that uses screenly.

Add installer for libraspberrypi0 and ifupdown, also chmod vchiq

---

server.py

Ref #1024
*IN:*
```
curl \
-H "Content-Type: multipart/form-data"  \
-X POST \
-F "file_upload=@test.jpg" \
http://x.x.x.x/api/v1/file_asset
```
*OUT:*
```
"/home/pi/screenly_assets/77586f3c25094119a721d5d2db48b8cc.tmp"
```
*IN:*
```
curl \
-H "Content-Type: application/json" \
-X POST \
-d '{"duration": "10", "end_date": "2019-03-31T06:39:00.000Z", "is_active": 1, "is_enabled": 0, "is_processing": 0, "mimetype": "image", "name": "test.jpg", "nocache": 0, "play_order": 0, "skip_asset_check": "0", "start_date": "2019-03-01T06:39:00.000Z", "uri": "77586f3c25094119a721d5d2db48b8cc.tmp" }' \
http://x.x.x.x/api/v1.2/assets
```
*OUT:*
```
{"asset_id": "8754f372ac3241bd8b174d6ce37c490a", "mimetype": "image", "name": "test.jpg", "end_date": "2019-03-31T06:39:00+00:00", "is_enabled": 0, "nocache": …
```

Fix: UUID name for *.tmp asset when upload

---

lib/utils.py

Discussion: #1034
Before:
`max(list(gateways()['default']))` these part of code will always return an IPv6(10) family instead of IPv4 (2)
Now:
`get_node_ip()` function only uses the IPv4 family.

Fix: Correct ip displays on the splash page.

---

ansible/roles/screenly/tasks/main.yml

Discussion #1038 
Before
```
pi@raspberrypi:~ $ date
Fri Mar 22 02:26:31 -06 2019
pi@raspberrypi:~ $ docker exec screenly-ose-viewer date
Fri Mar 22 08:26:38 UTC 2019
```
Now
```
pi@raspberrypi:~ $ date 
Fri Mar 22 02:27:32 -06 2019
pi@raspberrypi:~ $ docker exec screenly-ose-viewer date   
Fri Mar 22 02:27:35 -06 2019
```

Fix: Docker containers timezone are now synchronized with the host

---

lib/errors.py
server.py
settings.py
viewer.py

Feature request: #916
**In:**
```
pi@raspberrypi:~ $ curl http://127.0.0.1:8080/api/v1/viewer_current_asset
```
**Out:**
`
{"asset_id": "e6d61798365d4b3f88c64faa6ade8bc0", "mimetype": "webpage", "name": "Screenly Weather Widget", "end_date": "2024-11-23T21:21:34+00:00", "is_enabled": 1, "nocache": "", "is_active": 1, "uri": "https://weather.srly.io", "skip_asset_check": 0, "duration": "10", "play_order": 0, "start_date": "2018-11-23T21:21:34+00:00", "is_processing": 0}
`

New endpoint: viewer's currenlty asset

---

lib/utils.py
server.py
templates/system_info.html

Refs: #1049 #971
This PR adds Mac address information to the system info page.

Feature: MAC address on System Info

---

ansible/roles/network/files/wifi-connect.service
lib/utils.py
server.py
start_resin_wifi.py
static/js/settings.coffee
static/js/settings.js
viewer.py

We have issues about that people can not reset the current point of wifi or when user change the location of the device it does not show a point(balena) to connect to a new access wireless point.
This PR solve these problems.
General tests were reproduced:
- Connected to the point, after IP was displayed. Then, the current connection was reset through `http://ip/settings`. After reboot we can see the hotspot page.
- Successfully connected to the wireless point. Turn off the Wi-Fi router. After reboot we can see the hotspot page.

Fix: wifi-connect and wifi reset

---

lib/diagnostics.py

This PR have the next edits:
- avoid `except:`
- added `try/except` for functions defining information about the device.

Fix: diagnostics's exceptions

---

.travis.yml
Dockerfile
ansible/roles/network/tasks/main.yml
ansible/roles/system/tasks/main.yml
ansible/site.yml
bin/install.sh
lib/utils.py
requirements.txt
server.py
start_resin_wifi.py
templates/settings.html
tests/updates_test.py
viewer.py

These edits helps for users w/out network-manager
Refs #1100, https://github.com/Screenly/screenly-ose/issues/1094#issuecomment-488649624
But as I said here https://github.com/Screenly/screenly-ose/issues/1094#issuecomment-488661111
https://github.com/balena-io/wifi-connect uses NetworkManager. In other words, the user will not be able to configure the wireless network.
Sum up: Yes , this PR will help users without NetworkManager, but I think we need to make NetworkManager by default.
@vpetersson Need your opinion.
UPD: Our latest image already includes NetworkManager.

Fix: work with nmcli

---

.dockerignore

When deploying the latest version of screenly to balenaCloud, if someone uses the `balena push` CLI deployment method, the CLI looks at `.dockerignore` and as such the `bin` directory which contains the `start-balena.sh` script is not copied. Removing `bin` from `.dockerignore` fixes this issue but I'm unsure if this breaks or conflicts with any other uses of this file.
Change-type: patch
Signed-off-by: Chris Crocker-White <chriscw@balena.io>

Remove bin from .dockerignore for balena push deploy

---

server.py

Currently the view index will generate an URL for the websocket, which is based on the physical address of the machine the server is running on. However when the server is running behind a reverse proxy like apache or nginx, we need to correct hostname in the request.
This pull request changes the generation of the websocket URL to use the hostname of the http request, which will be the ip if running natively without proxy and the hostname of the reverse proxy when being served through apache or nginx.

Allow connection to websocket when server is behind reverse proxy.

---

Dockerfile
Dockerfile.template
bin/install.sh

Ref https://github.com/Screenly/screenly-ose/pull/1139#discussion_r288925166
```
pi@raspberrypi:~ $ cat version.md 
Screenly version: master@76c881cc12a7ed93cf74547abec7961fe3a4bc18
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
```

Edit: version of screenly in install.sh

---

lib/backup_helper.py
server.py

Ref #1110
Example of backup name: `screenly-backup-2019-06-12T07-45-15.tar.gz`

Edit: backup archive name

---

static/css/screenly.css
static/sass/screenly.scss
templates/footer.html

Ref: #1097
- Now footer is sticky 
- no way to make a design for github button with https://buttons.github.io
- logo taken from `static/img`
Screenshot:

Redesign: footer

---

server.py
tests/server_test.py

Request on feature: #1195
Edits:
- The endpoint allows to PATCH all field except the following: asset_id, is_processing, mimetype, uri
- Added test `server_test.DBHelperTest.test_update_asset`

Endpoint: PATCH on assets

---

ansible/roles/screenly/files/screenly-celery.service
ansible/roles/system/tasks/main.yml
docker-compose.dev.yml
docker-compose.yml
requirements/requirements.txt
server.py

Edits: 
- Replaced rabbitmq by redis
- Fixed bug which was be the cause why we chosen rabbitmq
- celery result expires in 6 hours
Tested on:
- locally
- device
- balenaCloud
Screenshots:
Logs:
```
pi@raspberrypi:~/screenly $ celery -A server:celery status
worker@screenly: OK
1 node online.
```

Edits: redis broker instead of rabbitmq

---

server.py

This is useful for remote monitoring of Screenly instances. I just added it to the v1 API since the change is backward-compatible, but it could be modified to v1.1 or a separate API endpoint if needed.
Thanks!

Add "up to date" flag to info API.

---

bin/install.sh
requirements/requirements.txt

Edits:
- requirements.txt
- bin/install.sh
Some logs:
```
PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=87   changed=62   unreachable=0    failed=0    skipped=11   rescued=0    ignored=0   
+ sudo apt-get autoclean
Reading package lists... Done
Building dependency tree       
Reading state information... Done
+ sudo apt-get clean
+ sudo find /usr/share/doc -depth -type f '!' -name copyright -delete
+ sudo find /usr/share/doc -empty -delete
+ sudo rm -rf /usr/share/man /usr/share/groff /usr/share/info /usr/share/lintian /usr/share/linda /var/cache/man
+ sudo find /usr/share/locale -type f '!' -name en …
```

Fix: requirements.txt and update command in install file

---

ansible/roles/screenly/files/screenly-viewer.service
viewer.py

Bug: 
- The viewer starts showing the hotspot page before the server starts. Thus the hotspot looks broken.

Fix: viewer should wait for server

---

ansible/roles/splashscreen/tasks/main.yml

just minor fixes for handling deprecation warnings:
```
TASK [splashscreen : Installs dependencies (Jessie)] ***********************************************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name:
"{{ item }}"`, please use `name: ['fbi']` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
skipping: [localhost] => (item=[]) 
TASK [splashscreen : Installs dependencies (not Jessie)] ********************************************************************************************************* …
```

minor deprecation fix on Jessie block - master branch

---

ansible/roles/splashscreen/tasks/main.yml

minor fix for deprecation warnings:
```
TASK [splashscreen : Installs dependencies (Jessie)] ***********************************************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name:
"{{ item }}"`, please use `name: ['fbi']` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
skipping: [localhost] => (item=[]) 
TASK [splashscreen : Installs dependencies (not Jessie)] ******************************************************************************************************************* …
```

minor deprecation fix on Jessie block - experimental branch

---

ansible/roles/splashscreen/files/plymouthd.default
ansible/roles/splashscreen/tasks/main.yml
ansible/roles/system/tasks/main.yml

- Pi4 splashscreen fix
so I just installed master branch a few mins ago to start testing this again and looked at that file, the ShowDelay=0 that was originally supposed to be configured was not there at all, it was as if the file kept the original content and this file did not override it.. then I noticed this ShowDelay=2 was in the `/usr/share/plymouth/plymouthd.default` file and not in the `/etc/plymouth/plymouthd.conf` file.. which is the file that seems to mainly controls this.. meaning, I thought the /usr/share/ one would override the default one, but if I rename the default and restart, there is no splashscreen, which means the /etc/ one is the one that controls this so we should be editing that one instead.. plus this /etc/ location one gets called first from reading playmouth …

Update plymouth related tasks and files

---

requirements/requirements.viewer.txt

Should we make this `urllib3==1.25.11` change because of this error when building dockerfile.viewer alert?
```
Step 3/15 : ADD requirements/requirements.viewer.txt /tmp/requirements.txt
---> 393dbe215b07
Step 4/15 : RUN pip install --no-cache-dir -r /tmp/requirements.txt
---> Running in 2855e7a14bd5
...
...
requests 2.24.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.2 which is incompatible.
```

Update requirements.viewer.txt to specify urllib3 version

---

webview/README.md
webview/src/main.cpp

Fix: displaying local images with a new webview
Edits:
- Passing `--disable-web-security` to an application

Fix: displaying local images

---

webview/README.md
webview/src/main.cpp
webview/src/view.cpp

Edits:
- We don't need `--disable-web-security` anymore
- We don't pass `file://local_file` to `src`. Instead of this, we pass base64 to `src`

Fix: webview displays the local assets

---

ansible/roles/system/tasks/main.yml

Containerd requires cgroup memory enabled
See https://github.com/Screenly/screenly-ose/issues/1460

Enable cgroup in kernel for containerd

---

requirements/requirements.host.txt

need to specify version of pyrsistent because newer version is not compatible with python 2.7
pyrsistent installs as dependency of `jsonschema` which is auto installed as dependency of `docker-compose`
```
(from jsonschema<4,>=2.5.1->docker-compose==1.26.2->-r /home/pi/screenly/requirements/requirements.host.txt (line 3))\n  Downloading https://files.pythonhosted.org/packages/7d/ae/90ddcf28fb8eee5d4990920586d2856342e42faa95f39223f0b9762ef264/pyrsistent-0.17.2.tar.gz (106kB)\n\n:stderr: pyrsistent requires Python '>=3.5' but the running Python is 2.7.16\n"}
```

requirements.host needs specific pyrsistent version

---

docker/Dockerfile.nginx

This commit fixes an issue where the nginx container does not start
as a result of the nginx packaged with raspbian daemonizing by default,
as well as including a conflicting virtualhost config from under /etc/nginx/sites-enabled.
Therefore, this change disables nginx daemonizing
in identical manner to the nginx upstream docker containers
(https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile-debian.template#L106)
as well as removes the package default nginx virtualhost configuration.
Fixes #1504

Fix startup of nginx after base image changes

---

ansible/roles/screenly/files/screenly-host-agent.service
ansible/roles/screenly/vars/main.yml
ansible/roles/system/tasks/main.yml
docker-compose.yml
host_agent.py
server.py
templates/settings.html

This change implements a mechanism for executing a restricted set of commands on the host from within the screenly Docker containers by using a very simple host agent process, which requires only 2 packaged dependencies (python3 and python3-redis) from the standard Raspbian repositories.
Initially, this functionality is used to implement the previously disabled reboot and shutdown features. However, this could fairly easily be expanded to re-implement the USB asset loading functionality.
Furthermore, this change removes the reinstallation of build-essential, as /usr/lib/gcc/arm-linux-gnueabihf/4.9/cc1plus does not exist after reinstalling such and screenly builds without error.

Implement reboot and shutdown for Dockerized Screenly via host agent

---

docker/Dockerfile.viewer

This remediates an issue where the timezone used by the QTWebView instance within the viewer container is always UTC, regardless of the host timezone.

Remove /etc/localtime in viewer container, such that the Docker mount takes precedence

---

bin/build_containers.sh
docker/Dockerfile.server
docker/Dockerfile.viewer
requirements/requirements-websocket.txt
requirements/requirements.txt
requirements/requirements.viewer.txt
webview/Dockerfile
webview/README.md

* Closes #1593. (Kudos to @emilyyap for patch.)
* Rolls back a number of Python package updates as they were not available in Python 2.
I successfully built (and pushed) new containers on a Pi 4. For whatever reason, cross-compiling still doesn't work.

Fix container builds

---

balena.yml

I modified the `balena.yml` file to see the logo on balenaHub.
Change-type: patch
Signed-off-by: Marc Pous <marc@balena.io>

Update balena.yml to visualize the logo on balenaHub

---

.github/workflows/build-webview.yaml
.github/workflows/docker-build.yaml

* Resolves issue with mixing `paths` and `paths-ignore` ([example run](https://github.com/Screenly/screenly-ose/actions/runs/3322205561)).
* Adds more excludes

Makes path/path-ignore consistent

---

.github/workflows/docker-build.yaml

The `::set-output` feature has been [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This PR remove sthe use of this feature.

Removes `::set-output` feature

---

.github/workflows/build-balena-disk-image.yaml

Turns out we can simplify this a fair bit. 
Relevant conversation:
https://forums.balena.io/t/building-disk-images-i-e-preloading-with-github-action-fails/365245/9

Fixes Balena disk image build

---

bin/install.sh

Manually pins cryptography library to 38.0.2.
Closes #1654

Fixes installer

---

bin/build_containers.sh

Here's a snippet of the issue:
```
Dockerfile.test:76
--------------------
75 |     
76 | >>> RUN --mount=type=cache,target=/var/cache/apt \
77 | >>>     wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_107.0.5304.121-1_amd64.deb -O /tmp/chrome.deb && \
78 | >>>     apt-get install -y /tmp/chrome.deb
79 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_107.0.5304.121-1_amd64.deb -O /tmp/chrome.deb &&     apt-get install -y /tmp/chrome.deb" did not complete successfully: exit code: 100
Error: Process completed with exit code 1.
```
This might fix recent build-related issues. See links below for relevant CI runs:
- …

Don't build test container for non-x86 builds.

---

README.md
bin/build_containers.sh

Here's the sample usage of the script:
```bash
DOCKERFILES_ONLY=1 ./bin/build_containers.sh
```
The variable `DOCKERFILES_ONLY` should be set to a non-zero number. Otherwise, the script will still build the containers.

Add support for generating only Dockerfiles when running `bin/build_containers.sh`.

---

bin/build_containers.sh
bin/start_wifi_connect.sh
docker-compose.yml.tmpl
docker/Dockerfile.wifi-connect.tmpl

- Follow-up fixes to #1778
```bash
cd && \
echo "export CUSTOM_BRANCH='hf-wifi'" > .env && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/custom-install/bin/install.sh)
```
```
#16 [stage-0  7/12] RUN curl -sL -o /tmp/wifi_connect.zip "" &&     unzip -o /tmp/wifi_connect.zip -d /usr/src/app &&     rm /tmp/wifi_connect.zip
#16 ERROR: process "/bin/sh -c curl -sL -o /tmp/wifi_connect.zip \"\" &&     unzip -o /tmp/wifi_connect.zip -d /usr/src/app &&     rm /tmp/wifi_connect.zip" did not complete successfully: exit code: 3
------
> [stage-0  7/12] RUN curl -sL -o /tmp/wifi_connect.zip "" &&     unzip -o /tmp/wifi_connect.zip -d /usr/src/app &&     rm /tmp/wifi_connect.zip:
------
Dockerfile.wifi-connect:60
--------------------
59 |     
60 | >>> RUN curl -sL -o …
```

Fix issues with the image build CI action.

---

bin/start_wifi_connect.sh

Initialize `VERBOSE` to `true` by default to resolve `unbound variable` issue.

---

README.md

Inside `README.md`, edit the commands used to run unit tests locally. Environment variables starting with `SKIP_` must be set to skip images that are not needed during image builds.

Edit docs for running unit tests locally.

---

bin/install.sh

- Resolves the `permission denied while trying to connect to Docker daemon socket [...]` issue

Fix permission errors when starting the containers via `install.sh`.

---

viewer.py

- (Temporarily) fixes Screenly/Anthias#1679.
```bash
cd && \
echo "export CUSTOM_BRANCH='hotfix-video-playback'" > .env && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/custom-install-1/bin/install.sh)
```
Reboot the system, SSH into the device again, then run the following:
```bash
cd ~/screenly && \
sed -i 's/pull/build/g' bin/upgrade_containers.sh && \
sudo apt-get install -y --no-install-recommends jq && \
docker compose down && \
DOCKERFILES_ONLY=1 DEV_MODE=1 ./bin/build_containers.sh && \
./bin/upgrade_containers.sh
```

Fixes video playback issue in Raspberry Pi 4.

---

.github/workflows/build-balena-disk-image.yaml

- These changes are needed so that the Anthias images can be re-included in the Raspberry Pi Imager as options

Fix the CI pipeline that builds Balena images.

---

README.md
ansible/roles/network/tasks/main.yml
ansible/roles/screenly/tasks/main.yml
ansible/roles/splashscreen/tasks/main.yml
ansible/roles/system/tasks/main.yml
ansible/roles/tools/tasks/main.yml
ansible/site.yml
bin/install.sh

- Fixes Screenly/Anthias#1834
```bash
cd && \
echo "export CUSTOM_BRANCH='fix-installer'" > .env && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/fix-installer/bin/install.sh)
```

Fixes the Anthias installer so that it'll work on Debian Bookworm as well

---

README.md

Fix broken image links in `README.md`

---

ansible/roles/system/tasks/main.yml

* Fixes #1892, #1878
* Set path to `/boot/cmdline.txt` for Bullseye and older
* Set path to `/boot/firmware/cmdline.txt` for Bookworm
```bash
cd && \
echo "export CUSTOM_BRANCH='fix-1892'" > .env && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/custom-install-1/bin/install.sh)
```

Sets `cmdline.txt` path conditionally

---

.github/workflows/docker-build.yaml
bin/deploy_to_balena.sh
bin/upgrade_containers.sh
docker-compose.balena.dev.yml.tmpl
docker-compose.balena.yml.tmpl
docker-compose.yml.tmpl
docs/balena-fleet-deployment.md

* Fixes #1829
```bash
cd && \
echo "export CUSTOM_BRANCH='fix-1829'" > .env && \
bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/custom-install-1/bin/install.sh)
```

Allows support for 4k display  by increasing shared memory in viewer

---

lib/utils.py
server.py

* In the Integrations page (for devices running BalenaOS), **_Supervisor Version_** has a value of **_None_**.
* With the changes, the server code retrieves the version from the Supervisor API instead of the `BALENA_SUPERVISOR_VERSION`, which doesn't really exist as an environment variable inside the server container.

Fixes erroneous data in the Integrations page

---

viewer.py

- This fixes the HTTP 502 issue that happens in the viewer when it tries to query the server, which might not be ready yet.
- The Bad Gateway issue is evident in BalenaOS devices. It can happen on cases during updates, where the server isn't fully ready yet.
- The current implementation might raise a connection error, but it doesn't raise exceptions if the HTTP status code of the response is non-successful.

Fixes the `wait_for_server` function to handle non-success HTTP codes as well.

---

templates/settings.html

* Change input label for default asset duration to "Default duration (seconds)"
* Change input label for default streaming duration to "Default streaming duration (seconds)"

Modifies help text for duration settings

---

bin/build_containers.sh

* The build script fails when installing non-existing packages like `omxplayer` for x86.
* Those packages are not removed from the base Dockerfile.
* This shouldn't affect the Docker image CI builds.

Fixes container build script for development mode in x86

---

.github/workflows/docker-test.yaml
README.md

* The CodeQL job still needs investigating. Resolution will be done on a separate pull request.
* When changes are pushed to `master` (for example, when a PR is merged), the [unit test job](https://github.com/Screenly/Anthias/actions/workflows/docker-test.yaml) is not being triggered (looking at face value).
* Take note, however, that the [image build job](https://github.com/Screenly/Anthias/actions/workflows/docker-build.yaml) does a workflow call to the UT job, therefore running the tests.
* The link to the linter job is broken, thus replacing it with the link to the [Python linter job](https://github.com/Screenly/Anthias/actions/workflows/python-lint.yaml).

Fixes CI badge references so that statuses can be displayed properly

---

.github/workflows/codeql-analysis.yaml

* https://github.com/github/codeql/issues/8843
* https://dev.to/pwd9000/fgjgghjgh-19ka
Current badge statuses

Specifies permissions when doing CodeQL analysis via CI

---

requirements/requirements-websocket.txt
requirements/requirements.txt
requirements/requirements.viewer.txt

* `2.2.3` is the last release that supports Python 3.7.
* Werkzeug dropped support for Python 3.7 starting at `2.3.0`.

Bumps Werkzeug from 2.2.2 to 2.2.3

---

templates/settings.html

* I forgot to remove that [`highlight.js`](https://highlightjs.org/) code before merging #1970.

Removes unused JS code in `settings.html`

---

server.py

* When #1950 was merged, the `/api/docs` URL broke.
*The URL specified in the code (for the API docs) is dependent `get_node_ip`, which returns multiple IPv4 and IPv6 addresses (as a string, separated by spaces).
* This pull request removes that dependency, making the `API_URL` just `/api/docs` for flexibility.

Fixes broken API docs page

---

server.py
templates/splash-page.html

* [**Square brackets** must surround an IPv6 address](https://www.uptrends.com/support/kb/synthetic-monitoring/monitor-settings/using-an-ipv6-address-instead-of-a-domain-name) if it were to be used in a browser.

Fixes formatting of IPv6 addresses in the splash screen

---

ansible/roles/screenly/tasks/main.yml
bin/install.sh

* https://forums.screenly.io/t/settings-page-produces-a-504/1478/4
```
nico@raspberrypi3:~ $ sudo journalctl -fu anthias-host-agent
-- Journal begins at Wed 2024-07-03 17:14:43 PDT. --
Jul 17 09:22:01 raspberrypi3 systemd[1]: anthias-host-agent.service: Failed with result 'exit-code'.
Jul 17 09:22:11 raspberrypi3 systemd[1]: anthias-host-agent.service: Scheduled restart job, restart counter is at 58.
Jul 17 09:22:11 raspberrypi3 systemd[1]: Stopped Anthias Host Agent.
Jul 17 09:22:11 raspberrypi3 systemd[1]: Started Anthias Host Agent.
Jul 17 09:22:12 raspberrypi3 python[16784]: Traceback (most recent call last):
Jul 17 09:22:12 raspberrypi3 python[16784]:   File "/home/nico/screenly/host_agent.py", line 10, in <module>
Jul 17 09:22:12 raspberrypi3 python[16784]:     import netifaces
Jul …
```

Fixes failure to start the host agent service in Bullseye.

---

.github/workflows/docker-test.yaml
ansible/roles/system/tasks/main.yml
bin/build_containers.sh
docker/Dockerfile.base.tmpl
docker/Dockerfile.celery.tmpl
docker/Dockerfile.server.tmpl
docker/Dockerfile.test.tmpl
docker/Dockerfile.viewer.tmpl
docker/Dockerfile.websocket.tmpl
docker/Dockerfile.wifi-connect.tmpl
docs/developer-documentation.md
lib/media_player.py
nose2.cfg
requirements/requirements-websocket.txt
requirements/requirements.dev.txt
requirements/requirements.txt
requirements/requirements.viewer.txt
requirements/requirements.wifi-connect.txt
tests/scheduler_test.py
tests/splinter_test.py
tests/updates_test.py
tests/viewer_test.py
viewer.py

* Resolves #1753
* Depends on #1982
- The webview can't start properly because it's searching for `*.so` files that are missing.
- Consider using Poetry &mdash; will be addressed in #1985 
* Moving away from OMXPlayer to VLC requires an upgrade from Buster.
* VLC playback in Buster is not possible, as per testing things quickly.
* One of the benefits of upgrading Python from

Upgrade containers to use Bookworm

---

bin/build_containers.sh

* The upgrade of the viewer container from Buster to Bullseye caused the Pi 1 builds to fail.
* This pull request removed `libssl1.1` from the list of APT packages to be installed.

Removes non-existing APT package `libssl1.1` for Pi 1 builds

---

.github/workflows/docker-build.yaml
.github/workflows/python-lint.yaml

* Bumps linter's Python version from 3.7 to 3.11
* Included `python-lint.yaml` in the files to be ignored for the `docker-build.yaml` workflow.

Bumps Python version used by the linter to 3.11

---

viewer.py

* Increases timeout of the Balena API call (for device info) from 30 to 90.

Fixes splash screen issue on Pi 2 devices running BalenaOS

---

lib/media_player.py
tests/scheduler_test.py
tests/viewer_test.py

* The default audio device (if not specified) is headphones (for BalenaOS devices) and HDMI (for Raspberry Pi OS devices), thus explicitly stating the ALSA output device based on app settings.

Modifies audio output based on app settings and Pi version

---

bin/build_containers.sh

* https://github.com/Screenly/Anthias/actions/runs/10218632753/job/28275365903

Removes Docker repo/tag names that causes error when pushing to Docker Hub

---

anthias_django/settings.py

* Adds properly-formatted IPv6 addresses in `ALLOWED_HOSTS` in Django settings

Ensures that the web UI is accessible via IPv6 addresses as well

---

lib/diagnostics.py
server.py
templates/system-info.html

* Fixes #1999
* The value for **_Monitor Info_** depends on the output of the `tvservice` command, which was dropped in **_Bookworm_**.

Removes Monitor Info from the System Info page

---

viewer.py

* See this [forum discussion comment](https://forums.screenly.io/t/after-booting-the-pi-if-the-asset-set-is-a-single-image-it-doesnt-display-the-screen-remains-dark-with-only-the-small-purple-screenly-logo-in-the-center/1166/28?u=nicomiguelino) for the solution.
* Fixes #1882
* Added a delay before the asset loop starts

Fix asset not being displayed for single-asset playlists

---

lib/media_player.py
tests/scheduler_test.py
tests/viewer_test.py
viewer.py

* Using the singleton pattern for the media player instance will help us avoid doing mocking (in tests) at module level.
* It's unpleasant to see a mock statement in the same level as the file-level imports in tests.

Adopt a singleton pattern for the media player instance

---

viewer.py

The issue (see logs for details) happens during a fresh install on both Raspberry Pi OS and Balena OS instances.
```
nico@raspberrypi4:~/screenly $ sudo docker compose logs -ft anthias-viewer
anthias-viewer-1  | 2024-08-29T01:12:50.234199929Z ./bin/start_viewer.sh: line 39: /sys/fs/cgroup/memory/memory.swappiness: No such file or directory
anthias-viewer-1  | 2024-08-29T01:12:53.257390741Z Loading browser...
anthias-viewer-1  | 2024-08-29T01:12:54.544799658Z Generating asset-list...
anthias-viewer-1  | 2024-08-29T01:12:54.608938054Z Viewer crashed.
anthias-viewer-1  | 2024-08-29T01:12:54.609054534Z Traceback (most recent call last):
anthias-viewer-1  | 2024-08-29T01:12:54.609077756Z   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 84, in _execute …
```

Initialize the `Scheduler` after the server starts.

---

pyproject.toml
viewer.py

* Moved the creation of a `Scheduler` object right after the server wait.
* Removed a unnecessary Poetry `script` from `pyproject.toml`.

Create a `Scheduler` instance only after server initialization completes

---

docs/developer-documentation.md

fix(docs): typo in developer-documentation.md

---

.github/workflows/docker-build.yaml
.github/workflows/docker-test.yaml
docs/developer-documentation.md
tests/settings_test.py
tests/splinter_test.py
tests/updates_test.py

* Using the `@skip` decorator will make running tests more simpler.
* With this, we can just run `nose2 -v` instead of `nose2 -v -A '!fixme'`
* The `docker-build.yaml` workflow was modified so that the CI won't build the Docker images if tests were added or modified.

Replace `nose` attributes with `unittest`'s `skip`

---

requirements/requirements.dev.txt
tests/updates_test.py

* Removed irrelevant test cases
* Added new test cases
* The existing test cases are already irrelevant as the `latest_anthias_sha`, formerly `latest_screenly_sha`, [was already decommissioned years ago](https://github.com/Screenly/Anthias/commit/2d81dc404ea5204d9f5e8c1109c5eb8ca975ad0f#diff-0bb30e60c9060eae4f3b622c188c4ed97bc18c04242404cd8a9a4098961082e4).

Add new tests for `updates_test.py`

---

ansible/roles/system/tasks/main.yml

* Added a new Ansible tag called `raspberry-pi`
* Renamed the tag `touches_boot_partition` to `touches-boot-partition` for consistency
* Added the `touches-boot-partition` to steps that need it
* This pull request can slim down changes made in #2048.

Add a new Ansible tag for Pi-related steps

---

server.py
templates/system-info.html

* The **Latest Viewer Logs** section has no practical use as of the moment.

Remove the Latest Viewer Logs section from the System Info page.

---

.github/workflows/python-lint.yaml
docs/developer-documentation.md

* Running `poetry install --with=[groups]` will also install dependencies outside of the specified group(s).
* If we want to install dependencies from specific groups, we have to run `poetry install --with=[groups]`.

chore(ci): replace `--with` with `--only` when installing specific deps

---

tests/test_app.py
tests/test_scheduler.py
tests/test_server.py

* The changes help minimize security-related issues found during code quality checks.

Use HTTPS instead of HTTP urls in unit tests

---

bin/install.sh

* Installing `python3-dev` prevents the following error when trying to install Python dependencies on a Raspberry Pi 2 running Bookworm.

Install `python3-dev` during installation to prevent errors

---

host_agent.py

The `fe80::` IP address is link-local and shouldn't be included in the splash page. (The address is not accessible from the browser.)
Stay tuned for the after photo.

Exclude link-local IP addresses in the splash page

---

tests/test_scheduler.py
tests/test_settings.py
viewer.py

* I resolved the merge conflicts but I failed to remove the import statement causing the error.

Fix import errors in `viewer.py`.

---

webview/build_x86.sh

Fix broken Qt download link; Qt 6.6. is now archived

---

bin/start_server.sh
server.py

* This pull request is sort of a follow-up to #2078.
* Currently, there's no way the user can specify `OVERWRITE_CONFIG`, `MANAGEMENT_USER`, and `MANAGEMENT_PASSWORD`, as `start_server.sh` is started when the server container starts, as specified in the server Dockerfile.
* Authentication credentials and most config changes can be done via the web interface for both RPi OS and BalenaOS.
* In `server.py`, the logic for creating config and asset directories were removed, as those directories were already created when `start_server.sh` runs.`
* https://github.com/Screenly/Anthias/pull/1409/files

Clean up unused/untraversed steps during server startup

---

bin/start_server.sh

* Only overwrite the main DB with the backup DB only if the latter is not malformed, which could be caused by an interrupted migration.
```
[Logs]    [2024-10-14T10:49:47.657Z] [anthias-server]   File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 90, in __exit__
[Logs]    [2024-10-14T10:49:47.657Z] [anthias-server]     raise dj_exc_value.with_traceback(traceback) from exc_value
[Logs]    [2024-10-14T10:49:47.659Z] [anthias-server]   File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 82, in _execute
[Logs]    [2024-10-14T10:49:47.659Z] [anthias-server]     return self.cursor.execute(sql)
[Logs]    [2024-10-14T10:49:47.660Z] [anthias-server]            ^^^^^^^^^^^^^^^^^^^^^^^^
[Logs]    [2024-10-14T10:49:47.660Z] [anthias-server]   File …
```

Fix Django DB migration

---

.github/workflows/build-balena-disk-image.yaml

* This will set the version of the devices using the image to a fixed one, even if new updates are released.

Configure preloaded Balena images to pin to a release

---

.github/workflows/docker-build.yaml
.github/workflows/docker-test.yaml
.github/workflows/python-lint.yaml
README.md
bin/build_containers.sh
bin/install.sh
bin/upgrade_containers.sh

* Now that [Anthias has migrated to Django](https://github.com/Screenly/Anthias/pull/2040), it is time that we remove all workflows that have anything to do with the `experimental` branch.

chore(cleanup): remove workflow related to the `experimental` branch

---

api/serializers.py
api/tests.py
docs/developer-documentation.md

* In #2040, the endpoints were modified so that
* `0` or `1` integer fields will be boolean fields AND
* the duration field will be integer fields (from char fields)
* Those are breaking changes, as there are already clients using those endpoints.
* A separate pull request will be created where a new set of endpoints will be created, labeled as `v2.0`.
* Changes to the Asset model will not be reverted.

Revert field-related changes in v1.2 endpoints

---

README.md
docs/README.md
docs/balena-fleet-deployment.md
docs/developer-documentation.md
docs/qa-checklist.md
docs/wifi-setup.md
webview/README.md

* Making use of alerts makes the repo docs less dull and more visible.
* See [this doc](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) about Markdown alerts for reference.

docs: make use of alerts in Markdown files

---

tools/image_builder/__main__.py

* Removes `libraspberrypi0` from `Dockerfile.viewer` for x86
* A follow-up pull request to #2060
* https://github.com/Screenly/Anthias/actions/runs/11724576804/job/32659200061#step:10:1605

fix: resolve issue when building the viewer Docker image for x86

---

.github/workflows/build-webview.yaml
.github/workflows/docker-build.yaml
.github/workflows/docker-test.yaml

* https://github.com/docker/setup-buildx-action/releases/tag/v3.7.1
* https://github.com/docker/setup-qemu-action/releases/tag/v3.2.0

chore(ci): bump Docker buildx and qemu actions to `v3`

---

anthias_django/settings.py
api/api_docs_filter_spec.py
api/tests.py
api/urls.py
api/views/mixins.py
api/views/v1.py
api/views/v2.py
static/js/anthias.coffee
static/js/settings.coffee

* Created the following endpoints:
- `/api/v2/backup`
- `/api/v2/recover`
- `/api/v2/reboot`
- `/api/v2/shutdown`
- /api/v1/file_asset
- `/api/v1/assets/content`
- `/api/v1/assets/order`
- `/api/v1/assets/control`
* Updated `settings.coffee` so that the settings page will use `v2` endpoints instead

api: create v2 endpoints in favor of the v1 endpoints currently used by Anthias from the Settings and home page

---

lib/media_player.py

* The issue only happens for **_x86 devices_**, which currently uses `ffmpeg` for video playback.
* The issue occurs when the **_Previous Asset_** or **_Next Asset_** button is clicked.
```
anthias-viewer-1  | 2024-11-25T23:27:50.417619808Z ./bin/start_viewer.sh: line 39: /sys/fs/cgroup/memory/memory.swappiness: No such file or directory
anthias-viewer-1  | 2024-11-25T23:27:50.890818091Z Loading browser...
anthias-viewer-1  | 2024-11-25T23:27:51.906726835Z Current url is http://anthias-nginx:80/static/img/standby.png
anthias-viewer-1  | 2024-11-25T23:27:51.919543035Z Generating asset-list...
anthias-viewer-1  | 2024-11-25T23:27:51.926753338Z Current url is http://anthias-nginx:80/splash-page
anthias-viewer-1  | 2024-11-25T23:27:56.220001577Z pkill: killing pid 24 failed: Operation not …
```

fix: add nullity check before calling `FFMPEGMediaPlayer.run.kill()`

---

ansible/roles/screenly/tasks/main.yml
docker-compose.yml.tmpl

Some x86_64 mini pc's need an `~/.asoundrc` file within the `viewer` container for sound output to work. This PR enables support for setups that need an `~/.asoundrd`.
This has been tested with a [MeLE PCG02 Mini PC 'Stick'](https://mele.cn/product/127-en.html). The `~/.asoundrc` this device needs is:
```
pcm.!default {
type hw
card 0
device 1
}
ctl.!default {
type hw
card 0
device 1
}
```

Add support for asoundrc

---

lib/utils.py

* Replaced `-f`/`--format` with more specific parameters

fix: videos downloaded via `yt-dlp` doesn't have audio

---

.github/workflows/docker-build.yaml
docker/Dockerfile.dev

> Not enforcing HTTPS here might allow for redirections to insecure websites. Make sure it is safe here.
* https://sonarcloud.io/project/security_hotspots?id=Screenly_screenly-ose&branch=master&issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&tab=how_to_fix

fix: enforce HTTPS when using `curl` to install Poetry

---

templates/settings.html

I accidentally pasted Ansible code in the `settings.html`.

chore: cleanup unnecessary code from the settings HTML template

---

webview/docs/build_webview_for_pi5.md

This pull request adds the missing step (where an environment variable named `GIT_HASH` should be set properly before building and starting the containers) in the documentation for building a WebView binary for Pi 5.

docs: add missing step in docs for building WebView for Pi 5

---

.github/workflows/build-balena-disk-image.yaml

This pull request contains changes to the Balena disk image workflow.

chore(ci): add support for generating pre-built Pi 5 balenaOS images

---

.github/workflows/deploy-website.yaml

Bumps the following GitHub Actions:
* actions/configure-pages@v5 (from `v2`)
* actions/upload-pages-artifact@v3 (from `v1`)
* actions/deploy-pages@v4 (from `v1`)

chore(ci): bump GitHub pages actions to the latest version

---

.github/workflows/generate-openapi-schema.yml

Bumps `actions/cache` from `v3` to `v4`

chore(ci): bump `actions/cache` to `v4`

---

api/views/v2.py

* #2190 
* The an `Asset` instance is created, the `start_date` and `end_date` are still read as `str`s.
* We need to refresh the `asset` from the database.
Include any additional information that you think is necessary for this pull request, including screenshots of the changes that you have made.

fix: error: "'<' not supported between instances of 'str' and 'datetime.datetime'"

---

.github/workflows/build-webview.yaml
.github/workflows/generate-openapi-schema.yml

Bumped `actions/upload-artifact` from `v3` to `v4`

chore(ci): bump `actions/upload-artifact` to `v4`

---

.github/workflows/build-webview.yaml
.github/workflows/generate-openapi-schema.yml

Bumps `actions/upload-artifact` from `v3` to `v4`.

chore(ci): bump `upload-artifact` action to `v4`

---

tools/image_builder/__main__.py
tools/image_builder/utils.py

* Screenly/Anthias#2196
Run the following commands on your Raspberry Pi 4
```bash
cd && bash <(curl -sL https://raw.githubusercontent.com/nicomiguelino/Anthias/refs/heads/test-fix-pi4-balena-deployment/bin/install.sh)
```
Target platform for Pi 4 Docker images was changed from `linux/arm/v8` to `linux/arm64/v8`.

fix: set target platform of Pi 4 images to `linux/arm64/v8`

---

.github/workflows/docker-build.yaml
.github/workflows/docker-test.yaml
.github/workflows/generate-openapi-schema.yml

Bumps CI runner OS to Ubuntu 24.04

chore(ci): bump runner OS to Ubuntu 24.04

---

.github/workflows/ansible-lint.yaml
.github/workflows/build-balena-disk-image.yaml
.github/workflows/build-webview.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/deploy-website.yaml
.github/workflows/javascript-lint.yaml
.github/workflows/python-lint.yaml
.github/workflows/sbom.yaml

Updates the rest of the GitHub Actions workflow files so that the CI runners will use Ubuntu 24.04 when running jobs.

chore(ci): bump runner OS to Ubuntu 24.04 for the remaining workflows

---

docker/Dockerfile.server.j2

Docker image builds are failing in CI. See the following CI run for details: https://github.com/Screenly/Anthias/actions/runs/13162811771
* Updated the server Dockerfile to install dependencies of `nodejs` and `npm`.

fix: install `nodejs` and `npm` dependencies

---

.github/workflows/docker-build.yaml
docker/Dockerfile.server.j2

* The GitHub Actions workflow for building the Docker images is broken.
* The build process stops at building the Docker image for the `server` service.
* Enabled installation of recommended packages when installing `nodejs` and `npm` during the first stage in `Dockerfile.server`.
* See the following CI run for proof: https://github.com/Screenly/Anthias/actions/runs/13185633333

fix: attempt to fix the CI pipeline for building Docker images

---

ansible/roles/system/tasks/main.yml
bin/upgrade_containers.sh

* Updates the installer so that an `arm64` version of Docker will be installed for Pi 4 devices running Raspberry Pi OS Lite.

chore: install the ARM64 version of Docker for Pi 4 running 64-bit

---

bin/install.sh
bin/upgrade_containers.sh
lib/device_helper.py

* https://github.com/Screenly/Anthias/issues/2217
Updated checks across relevant files in the codebase so that Raspberry Pi compute module devices would be supported as well
* See https://forums.screenly.io/t/challenges-with-installing-anthias-on-pi-5/1704 for details.

feat: add support for compute module devices

---

.github/workflows/build-webview.yaml
webview/Dockerfile.x86
webview/README.md
webview/build_webview_with_qt5.sh
webview/build_x86.sh
webview/src/mainwindow.cpp

Building Qt from source can be a bit time-consuming, so we'll just be using the prebuilt Qt binaries from the Anthias releases.

chore: add support for building just the WebView binaries

---

.github/workflows/build-webview.yaml

Sets `GIT_HASH` to the shorter version of the current commit hash

chore(ci): set GIT_HASH to a short commit hash

---

.github/workflows/build-webview.yaml
webview/build_webview_with_qt5.sh

- Added a conditional step that creates a GitHub release when a new tag (e.g., `WebView-vM.m.p`) was pushed
- Included Qt 5 binaries/libraries in the archive

chore(ci): add a conditional step for creating a release on tag push

---

.github/workflows/build-webview.yaml

See this [CI run](https://github.com/Screenly/Anthias/actions/runs/13875686684) for details.
* Added a step that inspects the directory where the WebView files are built
* Updated paths for files to be uploaded to a new release

chore(ci): updated paths for files to be uploaded to a new release

---

.github/workflows/build-webview.yaml

- Updates the workflow file so that a x86-compatible WebView binary can be built as well

chore(ci): add pipeline for building x86-compatible WebView

---

.github/workflows/build-webview.yaml

- Sample CI Run: https://github.com/Screenly/Anthias/actions/runs/13877662361/job/38832103974

chore(ci): fix permission issues when creating webview releases

---

.github/workflows/build-webview.yaml

- Adds support for building a WebView binary compatible with the Raspberry Pi 5
- Sets `COMPOSE_BAKE=true` for x86 and Raspberry Pi 5 builds

chore(ci): add a pipeline for building pi5-compatible webview

---

.github/workflows/docker-build.yaml
.github/workflows/docker-test.yaml
tools/image_builder/__main__.py

- Cache restores are not strict for certain platforms.
- For instance, for a Pi 5 build, if there's a cache miss on the first pattern (e.g., `[runner_os]-buildx-pi5-[sha]`), the next less-specific pattern will be considered (i.e., `[runner_os]-buildx-*`), which is problematic as an x86 or Pi 4 cache (for instance) can be restored.
- Ensures that there are dedicated cache directories for each of the supported platforms (Pi 1-4, Pi 5, x86)

chore(ci): fix caching of Docker image builds

---

ansible/roles/screenly/tasks/main.yml
bin/install.sh
requirements/requirements.host.txt

- Fixes #2233
- Reverts `ansible-core` from `2.17.7` to `2.15.9` for Bullseye and older
- Bumps `ansible-core` to `2.18.3` for Bookworm

fix: installing Anthias in Bullseye

---

bin/install.sh
bin/upgrade_containers.sh

- Fixes #2250 
Updates the installer script so that images can be pulled successfully from Docker Hub.

fix: stick to `pi4` for Anthias version v0.19.5 and older

---

webview/src/mainwindow.cpp
webview/src/view.cpp
webview/src/view.h

- Fixes #2051
- This is an attempt to avoid a gap (in a form of a black screen) between assets.

fix: black screen after each image

---

webview/src/view.cpp

#2253 fixed #2051, but let's say you have the following playlist items (in order):
- Image Asset 1
- Web Asset 1
- Image Asset 2
- Web Asset 2
When Web Asset 2 is about to be displayed, Web Asset 1 can still be seen for a quick moment.
Waits for a web asset to be finished (loading) before showing it.

fix: only display a web asset when it has finished loading

---

api/views/v2.py

- If basic authentication is enabled, anyone can still access the `/api/v2/device_settings`
- Adds the `authorized` decorator to the endpoint function

fix: ensure authentication for the device settings endpoint

---

api/serializers/mixins.py
api/serializers/v2.py
api/views/mixins.py

Given that I'm starting Anthias in development mode, I'm getting the following output when I access `http://localhost:8000/api/docs/` from my browser:
```
anthias-server-1  | 2025-04-17T20:41:04.204481706Z [17/Apr/2025 20:41:04] "GET /api/docs/ HTTP/1.0" 200 727
anthias-server-1  | 2025-04-17T20:41:04.255157863Z /usr/src/app/api/serializers/v2.py: Warning [AssetListViewV2 > AssetSerializerV2]: unable to resolve type hint for function "is_active". Consider using a type hint or @extend_schema_field. Defaulting to string.
anthias-server-1  | 2025-04-17T20:41:04.259849129Z /usr/src/app/api/views/v2.py: Error [PlaylistOrderViewV2]: unable to guess serializer. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. Either …
```

chore: fix API docs warnings

---

.github/workflows/build-balena-disk-image.yaml

- It can be tiresome to write release notes from scratch. It would be better if a release note will be generated and that it can be edited later if needed.
- This PR aims to reduce manual busy work when creating releases.
- Configures the workflow that builds Balena disk images to generate release notes when creating a new release

chore(ci): automatically generate release notes when creating a new release

---

api/serializers/v2.py
api/tests/test_v2_endpoints.py
api/urls/v2.py
api/views/v2.py

- Creates a new endpoint that returns data similar to those in the integrations page

api: write new endpoint for info about the Balena integration

---

api/tests/test_info_endpoints.py
api/views/mixins.py
api/views/v2.py

Updates the `GET /api/v2/info` endpoint so that the response includes the following new fields:
- Memory
- Uptime
- Device Model
- Anthias Version
- MAC Address

api: add new fields to the `GET /api/v2/info` endpoint response

---

static/sass/_styles.scss

- Made the width of the buttons in the settings page wider so that the look and feel is consistent across all sections

fix: make the minimum width of the settings buttons wider

---

api/serializers/v2.py

- Allow blank inputs for `player_name` when calling `PATCH /api/v2/device_settings`

fix: allow blank values for `player_name` for `PATCH /api/v2/device_settings`

---

api/serializers/v2.py
api/tests/test_v2_endpoints.py
api/views/v2.py

- Updated `GET /api/v2/device_settings` so that `username` will be included in the response

api: update `GET /api/v2/device_settings` response

---

api/serializers/v2.py
api/tests/test_v2_endpoints.py

- Some Balena-related environment variables might not be present, which could result to `getenv` calls returning `null`.
- Made the all response fields for the `/api/v2/integrations` endpoint nullable to prevent schema-related errors

api: make response fields for the integrations endpoint nullable

---

api/tests/test_v2_endpoints.py
api/views/v2.py

- Updated `PATCH /api/v2/device_settings` so that default assets can be created or removed

api: handle default assets in `PATCH /api/v2/device_settings`

---

.github/workflows/javascript-lint.yaml
docs/developer-documentation.md
package.json

Replaced `npm run lint` with `npm run lint:check` and `npm run lint:fix`

chore(ci): replace NPM `lint` script with `lint:check` and `lint:fix`

---

static/src/components/settings.jsx

- Raspberry Pi 5 doesn't have a **_3.5mm jack_**, yet it appears as an option for **_Audio output_**.
- Update the `Settings` component so that **_3.5mm jack_** won't be displayed as a drop-down option for Raspberry Pi 5 devices.

fix: '3.5mm jack' should not be an option for the Raspberry Pi 5

---

.github/workflows/build-balena-disk-image.yaml

This is an attempt to make the file size of release images smaller than ~2GB.

fix: replace `zip` with `xz` for compression

---

.github/workflows/build-balena-disk-image.yaml

Replaced `zip` with `zstd` for compressing Balena disk images

chore(ci): use `zstd` instead of `zip` for compressing Balena images

---

api/serializers/v2.py

The following issue happens when Anthias is installed via the release images, which are pinned to specific releases.
```
GET /api/v2/integrations
```
```
HTTP 500 Internal Server Error
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"error": "{'balena_device_name_at_init': [ErrorDetail(string='This field may not be blank.', code='blank')]}"
}
```
Modified `balena_device_name_at_init` to allow blank values.

fix: integrations page not showing up on Balena instances

---

static/src/components/system-info.jsx

- System memory values are obtained from the back-end in bytes.
- Those values were bit shifted by 20 digits to the right.
- Since bit shift operations were done, it's more appropriate to use MiB instead of MB.
- Change the unit for system memory from megabytes (MB) to mebibytes (MiB). More details can be found [here](https://www.iec.ch/prefixes-binary-multiples).

fix: change unit for memory from MB to MiB

---

static/src/components/integrations.jsx

For Anthias instances installed using release images, Device Name is being shown in the Integrations page even if it's blank.
- Updates the Integration pages so that Device Name won't be shown if it's blank

fix: don't show Device Name in Integrations page if blank

---

.github/workflows/generate-openapi-schema.yml

When the [**Build Balena Disk Images**](https://github.com/Screenly/Anthias/actions/workflows/build-balena-disk-image.yaml) gets triggered, it calls the [**Generate OpenAPI Schema**](https://github.com/Screenly/Anthias/actions/workflows/generate-openapi-schema.yml) workflow first, which creates a release.
However, that a release gets created from the OpenAPI workflow, [generateReleaseNotes](https://github.com/ncipollo/release-action#:~:text=generateReleaseNotes) is not enabled. It's only enabled when called from the **Build Balena Disk Images** workflow.
Since the OpenAPI workflow gets called first, it's important to enable automatic release generation from there as well.

chore(ci): enable generation of release notes for OpenAPI workflow

---

anthias_app/admin.py
anthias_app/models.py
docs/developer-documentation.md

Registered the `Asset` model to the Django admin site so that it will be visible from there.

chore: register the `Asset` model to the Django admin site

---

eslint.config.mjs
static/src/components/edit-asset-modal.jsx

For instance, setting "Play for" to "1 Week" when editing assets won't save the changes in the end date.
Fixes handling of the "Play for" field when editing assets.

fix: fix handling of "Play for" when editing assets via form

---

static/sass/_styles.scss

The toggle switches in the home page and the settings page are styled inconsistently:
- Emits a blue circle (with a ripple effect) when the switch is toggled.
- The outline of the circular part of the toggle switch becomes black when toggled.
We have to restyle those toggle switches to remove those so that it's as minimal as it could get.

feat: restyle toggle switches for consistency

---

static/src/components/asset-row.jsx
static/src/components/settings.jsx
static/src/constants.js
webpack.common.js

SweetAlert2 alerts for confirming the result of deleting assets or saving player settings are only showed for 2 seconds.
- Increased the alert timer duration from 2 seconds to 3.5 seconds.

feat: increase SweetAlert2 timer durations from 2s to 3.5s

---

static/src/store/index.js
webpack.dev.js
webpack.prod.js

If the [Redux DevTools](https://chromewebstore.google.com/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) extension is installed (for instance, in Chrome), the extension is enabled even if the web UI is in production.
- Updated settings so that Redux DevTools will be enabled in development and disabled in production
- This is a do-over of #2334

chore: disable Redux DevTools in production

---

static/src/components/app.jsx
static/src/components/asset-modal/use-asset-form.js
static/src/components/settings.jsx
static/src/store/assets/asset-modal-slice.js
static/src/store/index.js
static/src/store/settings/index.js

`settings.jsx` already has ~770 lines of code, which could get harder to manage in the future.
Created a Redux store for the Settings page.
Moved most of the business logic from the Settings component to the new Redux store.

chore: refactor the Settings component

---

.github/workflows/build-balena-disk-image.yaml

- Fixes #2339 
- This pull requests automates the creation of a `docker-tag` file to prevent creating it manually when creating a new release.

chore(ci): add a job for creating a `docker-tag` file

---

static/src/components/settings/authentication.jsx
static/src/store/settings/index.js

In the Settings page:
- The Current Password field doesn't show up when the Settings page loads, given that basic authentication is enabled.
- Updated the condition(s) for showing the Current Password field

fix: Current Password field not showing if basic auth is enabled

---

static/src/components/empty-asset-message.jsx

Added missing spaces and punctuation to the message that shows up when there are not assets

fix: add missing spaces and punctuations

---

static/src/components/settings/audio-output.jsx
static/src/components/settings/date-format.jsx
static/src/components/settings/default-durations.jsx
static/src/components/settings/index.jsx
static/src/components/settings/player-name.jsx
static/src/components/settings/toggleable-setting.jsx

- `settings.jsx` has around 300 lines of code. With this PR, lines were reduced to ~200.
- Serves as a follow-up PR to #2341 
- Created new components off of `Settings`:
- `PlayerName`
- `DefaultDurations`
- `AudioOutput`
- `DateFormat`
- `ToggleableInput`&mdash;a reusable component used for on-off settings like splash screen, default assets, 24-hour clock, and debug logging

chore: split `Settings` into multiple components (follow-up)

---

.github/workflows/build-balena-disk-image.yaml
.github/workflows/generate-openapi-schema.yml

Updated the release for creating a new release so that creating a GitHub release will only be called once.

chore(ci): modify workflow for creating a new release

---

.github/workflows/build-balena-disk-image.yaml

- https://github.com/Screenly/Anthias/actions/runs/15717904106
- Updated the value of `path` for the "Upload artifacts" step

chore(ci): fix path wildcards used for uploading release artifacts

---

.github/workflows/build-balena-disk-image.yaml

- [v0.20.2](https://github.com/Screenly/Anthias/releases/tag/v0.20.2) didn't include `anthias-api-schema.json` when the release was generated automatically. We have to upload it manually for that version.
- The issue started to happen when the workflow file was refactored.
- Included the generated OpenAPI schema file in the files to be uploaded for a new release

chore(ci): include Anthias' OpenAPI schema in the release workflow

---

.github/workflows/deploy-website.yaml
raspberry_pi_imager/bin/build-pi-imager-json.py
website/README.md

- https://github.com/Screenly/Quality-Control/actions/runs/14985155822/job/42097579393
- Unable to access `https://anthias.screenly.io/rpi-imager.json`.
- Fixed the website deployment workflow so that it would include the `rpi-imager.json` again
- Fixed the Python script that generates the JSON so that it would include the `.zst` images in the list

chore(ci): fix missing RPi Imager JSON URL

---

static/src/components/edit-asset-modal.jsx

- Disabled editing of duration for video assets

fix: disable editing of duration for video assets

---

docker/Dockerfile.server.j2

- Fixes Docker image [build failures](https://github.com/Screenly/Anthias/actions/runs/15859672589/job/44714146183) caused by merging #2359
- Copies `tsconfig.json` in production mode before building
```
#22 ERROR: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
------
> [node-builder 9/9] RUN npm run build:
1.611 [tsl] ERROR
1.611       TS18002: The 'files' list in config file 'tsconfig.json' is empty.
1.611 ts-loader-default_e3b0c44298fc1c14
```

fix: copy `tsconfig.json` when building Dockerfile.server in prod

---

static/sass/_styles.scss
static/src/components/edit-asset-modal/date-fields.tsx

The start and end date fields in the Edit Asset form looks crammed. Those inputs needs to be a bit wider to avoid the date values overflowing.
Increased the width of start and end date input fields.

fix: adjust the width of date and time fileds in Edit Asset form

---

package-lock.json
package.json
webpack.common.js

It's tedious to update import aliases/paths across multiple files&mdash;`tsconfig.json` & `webpack.common.js`.
**tsconfig.json**
```javascript
{
"compilerOptions": {
// ...
"paths": {
"@/components/*": ["static/src/components/*"],
"@/constants": ["static/src/constants.ts"],
"@/store/*": ["static/src/store/*"],
"@/sass/*": ["static/sass/*"],
"@/utils/*": ["static/src/utils/*"],
"@/types": ["static/src/types.ts"]
}
},
// ...
}
```
**webpack.common.js**
```javascript
module.exports = {
// ...
resolve: {
alias: {
'@/components': path.resolve(__dirname, 'static/src/components'),
'@/constants': path.resolve(__dirname, 'static/src/constants.ts'),
'@/store': path.resolve(__dirname, 'static/src/store'),
'@/sass': path.resolve(__dirname, 'static/sass'),
'@/utils': path.resolve(__dirname, …
```

chore: unify paths used for building front-end code

---

static/src/components/home.tsx
static/src/components/integrations.tsx
static/src/components/settings/index.tsx
static/src/components/system-info.tsx

- The page title is no longer displayed in the browser tab.
- https://forums.screenly.io/t/anthias-web-ui-custom-html-title/6436
This pull request adds the player name to page titles for the following&mdash;home, integrations, settings, and system info.

fix: include player name in page titles

---

.cursor/rules/general.mdc

The Cursor agent tries to run commands as if Anthias runs directly in host
Added a new Cursor rule to prefix such commands with Docker commands

chore: add cursor rules for running commands inside a Docker container

---

api/tests/test_info_endpoints.py
api/views/v2.py

Adds a new `ip_addresses` field in the response of `GET /api/v2/info`

feat: include IP addresses in system info endpoint

---

api/tests/test_info_endpoints.py
api/views/v2.py

Adds a `host_user` field in the response body of `GET /api/v2/info`

feat: include host username in info API endpoint

---

static/src/components/settings/index.tsx
static/src/components/settings/update.tsx

The "Upgrade Anthias" section in the Settings page disappeared when the front-end was migrated to React.
- Restored the "Upgrade Anthias" section in the Settings page
- Renamed "Upgrade Anthias" to "Update Anthias"
- There must be a way for the IP addresses to be retrieved via the REST API.

fix: restore "Upgrade Anthias" section in Settings page

---

webview/src/mainwindow.cpp
webview/src/mainwindow.h
webview/src/view.cpp
webview/src/view.h

- Reverts Screenly/Anthias#2378
- The WebView doesn't wait for the next webpage to preload.
- Say that web asset A and web asset B have zoom levels of 1.25 and 2.00, respectively. The playback of those assets won't be smooth, as if they're glitching and unexpectedly zooming in and out.
- A new PR will be create that will include the changes in this PR plus the necessary fixes.

Revert "feat: add WebView support for zoom level in web pages"

---

anthias_django/urls.py

`/admin/` will bring users to the Django Admin page while `/admin` will redirect them to somewhere else.
Updates URL mappings to redirect `/admin` to `/admin/`

fix: redirect `/admin` to `/admin/`

---

webview/src/view.cpp
webview/src/view.h

- Fixes #2381
- Updates the WebView so that the next web asset to be displayed will be loaded before it gets shown on the screen

fix: add WebView support for preloading web pages

---

api/serializers/mixins.py
static/src/components/add-asset-modal/file-upload-utils.ts

Adding an asset using a YouTube link fails.
Fixed handling of YouTube URLs in front-end and back-end so that the asset can be created successfully.

fix: adding a YouTube asset fails

---

webview/src/mainwindow.cpp

- Using frame buffer for display wouldn't work for x86 devices running balenaOS.
- With #2409, X11 will be used for display.
- Even though it works, the assets are not being displayed properly. They are scaled down to about 5%.
- This pull request forces full screen in the web view.

feat: force full screen for x86

---

.github/workflows/build-webview.yaml

Replaced `ncipollo/release-action` with GitHub CLI

chore(ci): create WebView release via GH CLI

---

.github/workflows/build-webview.yaml

Specifies GitHub token when creating release via GitHub CLI in a workflow

chore(ci): specify `GH_TOKEN`

---

.github/workflows/build-webview.yaml

https://github.com/Screenly/Anthias/actions/runs/16663093121/job/47164704634
```plaintext
echo "Processing artifacts for board: pi3"
if gh release view "WebView-v0.3.12" 2>/dev/null; then
echo "Release already exists, uploading assets for pi3..."
gh release upload "WebView-v0.3.12" \
build/webview-*.tar.gz \
build/webview-*.tar.gz.sha256 \
build/qt5-*.tar.gz \
build/qt5-*.tar.gz.sha256
else
echo "Creating new release for pi3..."
gh release create "WebView-v0.3.12" \
--prerelease \
--generate-notes \
build/webview-*.tar.gz \
build/webview-*.tar.gz.sha256 \
build/qt5-*.tar.gz \
build/qt5-*.tar.gz.sha256
fi
shell: /usr/bin/bash -e {0}
env:
GH_TOKEN: ***
Processing artifacts for board: pi3
Creating new release for pi3...
failed to run git: fatal: not a git repository (or any of the parent …
```

chore(ci): specify repo when running `gh release` subcommands

---

tools/image_builder/utils.py

Pins WebView version used by the viewer service to [v0.3.12](https://github.com/Screenly/Anthias/releases/tag/WebView-v0.3.12)

feat: forces WebView to display full screen

---

.github/dependabot.yml

- Changed the frequency of doing Dependabot updates from `weekly` to `daily`
- Added rules for GitHub Actions and Docker
- Groups dependency updates according to ecosystem (e.g., `npm`, `pip`, `docker`, `github-actions`)
- Removed excessive comments from `dependabot.yml`

chore(deps): increase freq of dep updates; group updates to fewer PRs

---

.github/dependabot.yml

- Ungroups `pip`-type Dependabot PRs
- There are some cases where bumping a Python dependency can cause failures during build time or runtime.
- Handling a large PR in this situation might be a bit convoluted.
- This is currently not the case for Node.js/JavaScript-type Dependabot PRs, as those changes only affects the frontend.

chore(ci): disable grouping of Python Dependabot PRs

---

.github/workflows/docker-build.yaml

- The Docker Image Build workflow fails to build the images and stops at the step where Poetry is being installed via GitHub Actions.
- Bumps Poetry version used in `snok/install-poetry@v1` to 2.1.3.

fix(ci): fixes workflow for Docker image builds

---

docs/x86-installation.md

Now that Debian 13 has been release, the previous link points to Debian 13 iso which is not compatible with current version of Anthias.
See #2493 for example.
Update the link to the latest Debian 12 release.
- [ x] I have performed a self-review of my own code.

docs: fix the Debian iso download link

---

.github/workflows/docker-build.yaml
docker/Dockerfile.server.j2
docker/Dockerfile.test.j2
docker/nodejs-install.j2
package-lock.json
tools/image_builder/__main__.py
tools/image_builder/utils.py

Node.js v18.x already reached its EOL.
This PR bumps Node.js version to v22.x.

chore: migrate Node.js from v18.x to v22.x

---

requirements/requirements.txt
requirements/requirements.viewer.txt

Fixes #2520
Merging the PR that upgrades `sh` from 1.8 to 2.2.2 broke the viewer. More details can be found at #2516.

fix: downgrade `sh` from 2.2.2 to 1.8
