Screenly/Anthias

requirements.txt, server.py
Use werkzeug for handle multipart instead of bottle. Now progressbar works as expected.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/317)
=> Re #123. Solves uploads of larger assets.

.travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/332)
=> explicitly set 'sudo: false' for migration to new travis infrastructure

misc/install.sh, misc/upgrade.sh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/342)
=> pull new sources before adding supervisor to autostart

static/js/screenly-ose.coffee, static/js/screenly-ose.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/331)
=> keep old name for asset on edit if new name is blank

README.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/355)
=> Add Api documentation

utils.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/335)
=> try do HEAD then do GET if fails for url check 

ansible/roles/splashscreen/files/asplashscreen, ansible/roles/splashscreen/tasks/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/388)
=> Hotfixes for splashscreen.

ansible/roles/system/files/rc.local, ansible/roles/system/tasks/main.yml
Brings in `/etc/rc.local` under management.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/389)
=> Solves #337. 

ansible/ansible.cfg, ansible/hosts, bin/install.sh
Simplify the Ansible setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/393)
=> Simplifies Ansible setup

ansible/handlers/main.yml, ansible/roles/screenly/tasks/main.yml, ansible/roles/system/tasks/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/397)
=> Minor installation enhancements.

server.py, viewer.py
* Fixes logic in splash page
* Bumps up copyright
* Minor copyright fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/398)
=> Fixes splash page when SSL is enabled

settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/406)
=> log to stdout instead of file

settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/407)
=> remove timestamp from logs

.gitignore, .travis.yml, Dockerfile, ansible/roles/rpi-update/tasks/main.yml, ansible/roles/system/tasks/main.yml, lib/diagnostics.py, lib/utils.py, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/410)
=> Improves diagnostics.

ansible/roles/screenly/tasks/main.yml, ansible/roles/system/tasks/main.yml, bin/install.sh
* Switches to official pip installation script [get-pip.py](https://pip.pypa.io/en/stable/installing/)
* Solves issues with missing locales (defaults to US/GB en)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/411)
=> Improves early dependency installation

server.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/414)
=> retrive logs from systemctl

server.py
Reverts wireload/screenly-ose#414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/415)
=> Revert "retrive logs from systemctl"

viewer.py
TODO: Needs to be tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/422)
=> Adds reload functionality of existing asset.

ansible/roles/system/files/01_nodoc, ansible/roles/system/tasks/main.yml, bin/install.sh
Recovers disk space from devices using the Ubuntu's [ReducingDiskFootprint](https://wiki.ubuntu.com/ReducingDiskFootprint).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/418)
=> Diskspace recovery

README.md, bin/install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/424)
=> Cleanup fix

ansible/roles/system/files/10-evdev.conf, ansible/roles/system/tasks/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/426)
=> Re-enables keyboard via evdev.

lib/utils.py, server.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/347)
=> Use custom text handler in bottle templates. Decode strings as unicode

server.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/429)
=> use systemctl for retrieve logs

server.py, viewer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/436)
=> Make update conditional on branch.

.travis.yml, bin/install.sh, requirements.txt
Adds `--syntax-check` for Ansible to Travis to make sure that we catch future errors in Ansible related to syntax.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/446)
=> Adds syntax check for Ansible on CI.

.travis.yml, tests/scheduler_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/447)
=> implements tests for scheduler

tests/settings_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/450)
=> implement tests for settings

bin/install.sh, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/452)
=> Refs #445. Solves pyasn dependency issue.

tests/request_test.py, tests/utils_test.py, tests/viewer_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/456)
=> Some additional tests

tests/updates_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/457)
=> tests for update

viewer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/458)
=> fix black screen between image assets

static/js/screenly-ose.coffee, static/js/screenly-ose.js, views/index.haml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/466)
=> make asset type immutable via edit

requirements.txt, static/css/screenly.css, static/sass/screenly.scss, views/index.haml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/470)
=> implement email subscription closes #420

static/js/screenly-ose.coffee, static/js/screenly-ose.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/475)
=> Correct behaviour for email subscribe form. closes #472

.travis.yml, static/spec/jasmine/phantom-console-reporter.js, static/spec/phantom-runner.js, static/spec/runner.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wireload/screenly-ose/476)
=> Travis CI for web tests. Closes #321

ansible/roles/system/tasks/main.yml, ansible/site.yml
Fix installation script: notify X restart
=> restart X via install/update

tests/scheduler_test.py, viewer.py
for https://github.com/wireload/screenly-ose/issues/490
=> Fix scheduler deadlines

README.md
Our code quality decreased during last commits. Let us include the badge to track the code quality.
=> Adds codacy badge

ansible/roles/network/files/screenly_net_mgr
See issue #522 for more details
=> Addition of shebang line to the init script for network configuration

viewer.py
https://github.com/wireload/screenly-ose/issues/515
=> escape @ in URI for UZBL

viewer.py
Reverts wireload/screenly-ose#526
=> Revert "escape only first @ in URI for UZBL"

.travis.yml, ansible/roles/screenly/files/screenly.conf, lib/utils.py, server.py, settings.py, static/js/screenly-ose.coffee, static/js/screenly-ose.js, tests/rtmplite/amf.py, tests/rtmplite/multitask.py, tests/rtmplite/rtmp.py, tests/splinter_test.py, viewer.py, views/index.haml, views/settings.haml
=> Add support for live streaming

docs/http-basic-authentication.md
To follow #495 I propose this documentation on how to enable HTTP basic authentication.
=> Added documentation about the HTTP basic auth

ansible/roles/screenly/files/screenly.conf, server.py, settings.py, tests/settings_test.py, views/index.haml, views/settings.haml, views/system_info.haml
Added a setting player_name which is displayed at the top of the schedule page and in html <title> to help identify which screen you are editing when multiple boxes are in use.
=> Added a setting for player name

lib/diagnostics.py, server.py, views/system_info.haml
New pull request replacing #601 which was missing recent merges
Feature #585 
Here's a screenshot showing two possible versions of the info table.
=> Display power

lib/utils.py, server.py, views/splash_page.haml
Refs https://github.com/Screenly/screenly-ose/issues/579
=> Improving network status detection

lib/utils.py, server.py
=> Fix network status detection

ansible/roles/screenly/tasks/main.yml, ansible/roles/system/tasks/main.yml
Refs https://github.com/Screenly/screenly-ose/issues/624
=> Fix network address detection for Stretch

requirements.txt, server.py
Refs https://github.com/Screenly/screenly-ose/issues/588
=> Add automatic API documentation

server.py, tests/viewer_test.py, viewer.py
Refs https://github.com/Screenly/screenly-ose/issues/591
=> Add API call for next/previous

README.md, server.py
Refs https://github.com/Screenly/screenly-ose/issues/639
=> Fix API documentation

server.py
=> Environment variable to get IP

bin/install.sh
=> Add reboot after installation

templates/system_info.html
Added player name to title and missing check for update available. I think these were lost in the move to flask.
=> Add missing title and update check to system info

Dockerfile.template, bin/start_resin.sh, docs/resin.md, viewer.py
Refs https://github.com/Screenly/screenly-ose/issues/657
=> Add support for Resin.io

lib/utils.py, server.py
Now for the YouTube video, we get the information about the duration through youtube-dl.
For all videos, we take the duration only once (first) and remain unchanged
Refs #600
=> Video duration changing

server.py, static/js/screenly-ose.coffee, static/js/screenly-ose.js, tests/request_test.py
=> Modernize assets endpoint

.travis.yml, Dockerfile, lib/utils.py
Refs https://github.com/Screenly/screenly-ose/issues/672
=> Gets info about a video through the ffmpeg

Dockerfile.template, ansible/roles/ssl/files/nginx_resin.conf, bin/start_resin.sh
=> Fix Resin issues

Dockerfile.template, bin/start_resin.sh, lib/utils.py, server.py, static/js/screenly-ose.coffee, static/js/screenly-ose.js, templates/index.html
solved the problem with wifi
added output of systemd logs
solved the problem related ws connection
Refs #674
=> Fix final Resin issues

static/js/screenly-ose.coffee, static/js/screenly-ose.js
=> Fix web asset issue

server.py
included in api device information, what is currently being loaded and size of space, to be used in external applications.
=> api add get info

lib/utils.py, server.py, settings.py, tests/viewer_test.py, viewer.py, websocket_server_layer.py
=> API call for navigate to any asset

docs/create_disk_image.md
=> Add auto-resize of disk on first boot

README.md
=> Fix status issue

Dockerfile.template
=> Fix API docs for Resin

ansible/roles/network/tasks/main.yml, ansible/roles/network/vars/main.yml, lib/utils.py, server.py, templates/hotspot.html, viewer.py
Now `resin-wifi-connect` is turned on only at the first boot and if there is no connection.
also it works in NOOBS
Refs #686 
Refs #691
=> Add resin-wifi-connect

ansible/roles/network/tasks/main.yml
The condition for ansible-task was missed. added
=> Fix install

bin/install.sh
Added removal of `wifi_set` after installation
Refs #725 #727 #728
=> Remove wifi_set after installation

requirements.txt, server.py, templates/hotspot.html
The network is renamed and the password for `wifi-connect` is added. in addition, a small refactoring
=> Enhancement for wifi connect

ansible/roles/system/files/rc.local
I think #744 related to wifi power management. 
added a command to disable this.
Refs #744 #285
=> Disable power management for wifi

ansible/roles/network/tasks/main.yml, ansible/roles/network/vars/main.yml
=> Updates wifi-connect

templates/settings.html
Hopefully fixes https://github.com/Screenly/screenly-ose/issues/775 (could it be that easy?)
=> Fix spaces in player name

bin/prepare_device_for_imaging.sh
Adding the sample assets using `prepare_device_for_imaging.sh` script
Refs #815
=> Adding sample assets using prepare script

static/css/screenly.css, static/sass/screenly.scss, templates/hotspot.html, templates/splash_page.html
=> Adaptive hotspot and splash page

viewer.py
=> Fixes display freezing

docs/create-disk-image.md
=> Updates create-disk-image.md

templates/settings.html
I missed a couple of classes when updating bootstrap.
=> Fixes settings.html

ansible/roles/network/tasks/main.yml, ansible/site.yml, bin/install.sh, server.py, templates/settings.html
Added a new install option that ignores all network stuff
=> Disable_manage_network install option

requirements.txt
It appears that wsgiref is not being used.  Sorry, yesterday's PR forgot to branch from the previous PR.
I have a friend who is installing these into restaurants and other places in the city.  I am probably going to be more involved in the code, since it's gaining popularity here.
=> Rm wsgiref

requirements.txt
Update dependencies to solve vulnerabilities.(Ansible, werkzeug and flask)
=> Solve security

static/css/screenly.css, static/sass/screenly.scss, templates/hotspot.html, templates/splash_page.html
=> Hotspot and splash page adaptive.

server.py, templates/hotspot.html, templates/index.html, templates/settings.html, templates/splash_page.html, templates/system_info.html
#861 
Add cache buster for flask.
=> Flask cache buster

static/css/screenly.css, static/js/screenly-ose.coffee, static/js/screenly-ose.js, static/sass/screenly.scss, templates/index.html
=> Add default loop times

static/js/screenly-ose.coffee, static/js/screenly-ose.js
=> Fix error when choose play for forever

static/js/screenly-ose.coffee, static/js/screenly-ose.js
I reproduced this #905 issue and confirm that.
This patch fix this problem.
=> Unable to modify manual dates for assets / Fix

ansible/roles/system/files/rc.local
PR for #817 
When I tried to reproduce the issue, I found that some edits had already been made in this commit https://github.com/Screenly/screenly-ose/commit/c57937fcf2a3de004b88625f8d71b41dc424c4c5#diff-51ee9359c6f236a2e9710703c82b04be , but also we can add some change for rc.local file.
=> If device not supported wifi

lib/utils.py, static/css/screenly.css, static/js/screenly-ose.coffee, static/js/screenly-ose.js, static/sass/screenly.scss
I tried to reproduced this #841 issue.
I got this error
Since the message is too big, it went out, and there is no way to close it.
Also all buttons was disabled.
I made some fixes, also added processing for this error.
=> Some fix with alert box

server.py, templates/settings.html
#910 and #911 
this patch fixed this problems.
=> Fix for default duration in settings page / No assets after save duration

bin/install.sh
These changes update the version ansible in the install script to the version of requirements.txt ansible.
=> Update version of ansible in bin/install.sh

ansible/roles/tools/files/nginx.conf, ansible/roles/tools/tasks/main.yml, ansible/site.yml, requirements.txt, tools/assets-migration-to-screenly-pro.py
Discussion about this tool #930 
This tool-script is written in python and and helps to transfer assets from Screenly-OSE to Screenly-PRO.
[Click](https://click.palletsprojects.com/en/5.x/) library used for CLI interface.
[Ngrok](https://ngrok.com/) used for serving the assets files locally.
=> Tool for migration assets to screenly-pro version

Dockerfile.template, bin/start_resin.sh
These edits allow build experimental branch on resin.
Build problems was discuss #906 and also #904.
=> Support for experimental branch build on resin.io

static/js/screenly-ose.coffee, static/js/screenly-ose.js, templates/index.html
These edits for #902.
Also added a fadeOut() for alert boxes with a timeout of 5 seconds.
@vpetersson Do you think this is a good solution?
=> Visual indicator after successfully uploading image

static/js/screenly-ose.coffee, static/js/screenly-ose.js, viewer.py
These some fixes for js and viewer.py.
Description of edits below.
=> Some fixes for js and viewer.py

requirements.txt
Update requests package to 2.20.0 version
=> Update requests in requirements.txt

static/js/screenly-ose.coffee, static/js/screenly-ose.js, templates/index.html
These edits for #818.
Also "duration" column, can be done as an option in the settings.
=> Add column 'duration' to asset row

bin/prepare_device_for_imaging.sh, server.py
- The name of the asset make unique only when you add them.
- Removed part of prepare_device_for_imaging.sh as https://github.com/Screenly/pi-gen has it.
=> Some fixes for asset unique name and prepare device script

lib/unicode_configparser.py, server.py, settings.py
An example of the problem #956
=> Supporting unicode for player name

bin/install.sh, requirements.txt
This update finally solves snyk [vulnerabilities](https://snyk.io/vuln/SNYK-PYTHON-ANSIBLE-72546).
Also tested with Screenlу update script.
=> Update ansible to 2.7.1

tests/viewer_test.py, viewer.py
=> Support unicode for title of webpage asset

ansible/roles/ssl/files/nginx.conf, ansible/roles/ssl/files/nginx_resin.conf
=> Add timeout backup for all nginx.conf files

bin/install.sh, requirements.txt
Updated packages in requirements.txt for passing snyk
=> Updated packages in requirements.txt for passing snyk

server.py
The problem is discussed here #998 
These edits just add the authentication for backup.
=> Authentication for backup

viewer.py
@vpetersson @ealmonte32
This [PR](https://github.com/Screenly/screenly-ose/pull/923)  for the problem when browser stuck at alert() prompt () etc. events
Unfortunately, this has given other problems, such as freezing and restarting the browser with non-standard encodings, since viewer read all the events of the browser.
These changes will revert PR above, but it will resolve issues for most users.
=> Fixes: viewer freezes and restarts in some cases.

ansible/roles/screenly/tasks/main.yml, bin/install.sh, requirements.txt, requirements.worker.txt
Edits:
1) Easy deploy celery branch on the device.
- `git checkout celery`
- `./bin/install.sh`
P.S. These are temporary edits.
2) Updated the redis version for `docker-compose up` build without errors.
=> Some edits for celery branch

server.py, static/js/settings.coffee, static/js/settings.js
PR #1010
@escoand 
Before:
```
screenly:
key: "uy7VWB4YAb638onHmW7P"
activate: false
copy: false
start_date: 1553191200
end_date: 1553796000
duration: 10
```
Now:
```
screenly:
key: "uy7VWB4YAb638onHmW7P"
activate: false
copy: false
start_date: 03/22/2019
end_date: 03/25/2019
duration: 10
```
=> UsbAssets: friendly time format in yaml file

lib/diagnostics.py, server.py, templates/system_info.html
=> Added 'Raspberry Model' and 'Screenly version' for system info page

bin/install.sh
Added the echo to user selection options to create simple file that users and System info can use to show current version of screenly.
=> Update install.sh to include OSE version file

lib/backup_helper.py
Backup and recover was rework there #987
This fix contains the missing part of the code.
=> Fix: backup recover for celery branch

server.py
=> Fix: extended character of file names

bin/install.sh, requirements.txt
This PR solves `snyk` vulnerabilities.
Tested through custom run_upgrade script.
=> Fix: snyk vulnerabilities

docker-compose.yml
Some small edits for docker-compose.yml
=> Fix: small edits for docker-compose.yml

viewer.py
Bug was made in the splash page url when resolving merge conflicts(In #1130)
=> Fix: splash page url

ansible/roles/network/vars/main.yml
Ref #1098
Edits:
- Balena wifi connect version updated to 4.2.5
=> Updates: balena wifi connect version to 4.2.5

server.py, viewer.py
Edits: 
- Code reuse
- Fixes error in balena
=> Fix: check_update

viewer.py
=> Fix: viewer_current_asset endpoint

bin/start_balena.sh
=> Fix: database migration on Balena

static/css/screenly.css, static/sass/screenly.scss, templates/index.html, templates/integrations.html, templates/settings.html, templates/system-info.html
=> Edits: added links on footer

templates/base.html, templates/footer.html, templates/head.html, templates/header.html, templates/index.html, templates/integrations.html, templates/settings.html, templates/system-info.html
=> Edits: refactor templates

static/js/settings.coffee, static/js/settings.js
Discussion #1047
Edits:
- Updated warning message when user shutdowns device from ui
=> Edits: warning message when shutdown

static/js/screenly-ose.coffee, static/js/screenly-ose.js
=> Edits: automatically set end date field

bin/install.sh, requirements.txt
Fix: https://snyk.io/vuln/SNYK-PYTHON-ANSIBLE-174932
=> Fix: snyk vulnerability

server.py, settings.py, static/js/screenly-ose.coffee, static/js/screenly-ose.js, static/spec/runner.html, templates/index.html, templates/settings.html
=> Feature: date format setting

auth.py, docs/wott-authentication.md, lib/utils.py, requirements.txt, server.py, templates/integrations.html, templates/settings.html
=> add integration tab extension for wott

start_resin_wifi.py
Ref #1186
Edit: Run wifi-connect in the background and check the network.
=> Fix: pass hotspot with active wired

ansible/roles/network/tasks/main.yml
=> Fix: network tasks of ansible

templates/index.html
=> Edit: no assets text

bin/install.sh
=> Fix: bump ansible in bin/install.sh

requirements.txt
Bump werkzeug 0.14.1 to 0.15.3
=> Edit: bump werkzeug to 0.15.3

bin/enable_ssl.sh, settings.py
Fixes:
- `./bin/enable_ssh.sh` was fixed
- Removed unused code after merge conflict
=> Fix: some fixes before release

docker-compose.yml
Edits:
- Small changes for `docker-compose.yml`
=> Fix: small fix for docker-compose.yml

ansible/roles/tools/tasks/main.yml
Ngrok was taken from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
=> Edit: ngrok will be copied locally

ansible/roles/screenly/files/default_assets.yml, ansible/roles/screenly/tasks/main.yml, bin/start_balena.sh, docker-compose.dev.yml, docker/Dockerfile.server.dev, server.py, settings.py, templates/settings.html
**Note**: If the PR makes sense, then should we delete `bin/prepare_device_for_imaging.sh` file?(Also we need to change same part in our pi-gen fork)
=> New: default assets

templates/footer.html
=> Added: Screenly App Store link on footer

bin/install.sh, templates/settings.html
=> Added: allows to choose production branch in the UI upgrade

docker-compose.dev.yml
=> Edits: docker-compose.dev.yml

templates/settings.html
=> New: ISO date format

bin/start_balena.sh, docker-compose.yml, settings.py, viewer.py, websocket_server_layer.py
Ref #1244
Edits: 
- Containers are isolated(Instead of network_mode: host)
Problems:
- The splash page shows the docker IP, not the device IP
- Swagger also refers to the wrong IP(need to edit the IP manually)
@vpetersson I need your review and opinion
=> Edits: docker-compose.yml

requirements/requirements.txt
Travis ci should be passed successfully
=> Fix: travis ci pass by updating the requirements.txt

docker-compose.yml, docker/Dockerfile.redis.template
=> Edits: redis container in docker-compose.yml

server.py
=> Edit: XSS escaping

requirements/requirements.txt, server.py, templates/system-info.html
=> Memory settings

docker-compose.demo.yml, templates/head.html
=> New: docker-compose.demo.yml

ansible/roles/network/vars/main.yml
Tested on real device. It works correct.
=> Edits: wifi connect version updated to latest

viewer.py
fix for uzbl '&' symbol parsing..
=> Update to viewer.py for "&" symbol parsing

bin/install.sh
updating to include rpi4 model
=> Update install.sh to include rpi4

ansible/roles/screenly/tasks/main.yml
=> Edits: build images locally

bin/install.sh
Minor cleanup on password checking block and experimental branch group revert
-made password checking into function
-use local variables instead of global
-reverting back git flag`force=no` until we find better solution for scenarios with local merge conflicts
=> cleanup and minor changes on password checking block

ansible/roles/system/tasks/main.yml, ansible/site.yml
Edits:
- Deleted nginx handler
- Added nginx to task that removes deprecated apt dependencies
=> Fix: remove system nginx

balena.yml
balenaHubify the balena.yml file
=> Update balena.yml for balenaHub

balena.yml
Further to #1419 for the master branch (only difference is Pi4 support removed)
=> Add balena.yml for balenaHub

webview/ScreenlyWebview.pro, webview/src/main.cpp, webview/src/mainwindow.cpp, webview/src/mainwindow.h, webview/src/view.cpp, webview/src/view.h
Docs: https://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html
Screenshots of the built webview:
=> Edits: updated webview to webengine syntax

README.md
=> Update to svg logo (experimental branch)

README.md
add balena install instructions
=> add balena install instructions

README.md
Renders better with less pixelation
=> Change to SVG balena logo

balena.yml
YAML expects a string for the dtparam here - so make a string and escape other inverted commas.
=> Make dtparam a string

balena.yml
=> Add raspberry pi 400 support

README.md
Add link to the balena.md file in docs section
=> Add link to balena.md

balena.yml
device type for Pi 400 changed name
=> device type has changed name

docs/developer-documentation.md
just updating/modifying some webview info and miscellaneous
=> fix webview documentation link and other misc

bin/install.sh
simple fix for plymouth splashscreen issue that has been affecting Pi4..
=> reinstalling plymouth to fix splashscreen issue

balena.yml
Just some housekeeping - we're updating the format of balena.yml to be futureproof and in the future the current format will be deprecated. Docs: https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/#balenayml-configuration-file
=> Update balena.yml to adhere to latest spec

docker-compose.override.yml
finalizes the volume fix for backup file function
=> fixes get backup function

lib/raspberry_pi_helper.py
Came across this revision in a Pi 4 I bought recently, was causing crashes in viewer.py
=> added revision c03114

ansible/roles/system/tasks/main.yml, bin/upgrade_containers.sh, requirements/requirements.host.txt
Addresses more bug fixes for installing on Pi 3
=> More install fixes

bin/start_viewer.sh, lib/github.py
This changeset improves behavior and recovery in 2 exceptional cases, namely:
- When the viewer container reaches the configure memory limit and the OOM killer is invoked, the process that is typically killed in this case is the Chromium renderer process launched by QTWebEngine causing the viewer container to continue running but display a blank white screen.  Therefore, this change increases the OOM score of the viewer container entrypoint script to the maximum value, guaranteeing that the viewer container is cleanly restarted after running OOM.
- When the Github API is unavailable or the remote branch name currently checked out in Screenly's working directory does not exist upstream, the current implementation of the update check either causes a 500 error and/or rapid requests to the …
=> OOM and Github API error handling improvements

webview/Dockerfile, webview/build_qt5.sh
* Changes have been made to avoid rewriting the script for new Qt versions.
* Changes were tested on the local machine.
=> Fix Qt Cross Compile Related Parts

.github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml, README.md, bin/prepare_test_environment.sh, bin/run_tests.sh, docker-compose.dev.yml, docker-compose.test.yml, docker/Dockerfile.test, tests/celery_tasks_test.py, tests/splinter_test.py, tests/updates_test.py
- Might fix #1604.
```bash
docker-compose -f docker-compose.test..yml up -d
docker-compose -f docker-compose.test.yml exec srly-ose-test bash bin/run_tests.sh
```
=> Bring back test suite runs on GitHub actions

README.md, bin/run_tests.sh
=> Update: how to run unit tests in README.md

bin/prepare_test_environment.sh, docker-compose.dev.yml, tests/celery_tasks_test.py
=> Fix failing tests in `test/celery_tasks_test.py`.

lib/utils.py, tests/splinter_test.py
=> Resolve broken import - `mplayer`

.github/workflows/build-balena-disk-image.yaml, .github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml
Attempts to add automatic build of (preloaded) disk images for Balena as per [this article](https://forums.balena.io/t/balena-preload-on-github-actions/337349/15).
=> Adds balena disk image build

lib/utils.py, requirements/requirements.txt, requirements/requirements.viewer.txt
=> Fix splash screen issue on Balena.

bin/prepare_test_environment.sh, docker/Dockerfile.test
Relevant parts of the code were removed. These will be brought back when `test_add_asset_streaming` is fixed.
=> Remove ffmpeg installation and setup from script & Dockerfile.

docker-compose.balena.yml
=> Add follow-up fixes to Balena splash screen error.

ansible/roles/system/tasks/main.yml, lib/media_player.py, viewer.py
=> Fix VLC video playback issues on Raspberry Pi 4. :wrench:

docker-compose.balena.yml, docker-compose.yml, lib/utils.py, server.py, templates/settings.html, viewer.py
=> Make use of the Supervisor API on device shutdown and/or reboot.

server.py, viewer.py
Just updating the copyright years.
=> Copyright year update

tests/updates_test.py
=> Run `updates_test.py` test cases in CI.

bin/build_containers.sh
```
Find out about the available commands by running:
$ balena help
For further help or support, visit:
https://www.balena.io/docs/reference/balena-cli/#support-faq-and-troubleshooting
git version 2.[30](https://github.com/Screenly/Anthias/actions/runs/4198089994/jobs/7282630131#step:6:31).2
Initializing SDK for [https://api.balena-cloud.com)](https://api.balena-cloud.com%29/)
Checking if a release has already been built.
Did not find existing release so building a new one.
Error:     Could not parse compose file
Error:       Invalid composition format
Error:     Not deploying release.
Error: Remote build failed
```
- https://github.com/Screenly/Anthias/actions/runs/4198089994/jobs/7282629982
- https://github.com/Screenly/Anthias/actions/runs/4198089994/jobs/7282630131
=> Include additional tags when building Docker images.

tests/updates_test.py
- Updates-related test cases seems to be very unstable.
=> Hotfix: Skip an update test case.

lib/diagnostics.py, lib/utils.py
- Fixes #1769 
- https://github.com/redis/redis-py/issues/910
- https://stackoverflow.com/questions/44026515/python-redis-keys-returns-list-of-bytes-objects-instead-of-strings
=> Resolve TypeError exception in `viewer.py` when serializing `bytes` in JSON.

lib/auth.py
=> Fix auth issue in Web UI.

docker/Dockerfile.nginx.tmpl
- Rename the NGINX config file from `anthiaas.conf` to `anthias.conf`.
=> Minor Fix: Rename NGINX config file.

README.md, docs/README.md
- Use `$` as prefix in shell commands.
=> Modify `README.md`

server.py
=> Fix byte-encoding issue that occurs when attempting to download an asset.

bin/build_containers.sh, static/css/screenly.css, static/sass/_styles.scss
=> Modify style of popover for the button used for deleting assets.

.github/workflows/build-balena-disk-image.yaml
- #1859 doesn't completely fix the issue, so I included follow-up changes.
=> Fix the CI pipeline that builds Balena images.

website/index.html
Fix "What hardware do I need to run Anthias?" -> remove raspberry Open source statement.
=> Fix "What hardware do I need to run Anthias?"

bin/build_containers.sh, bin/prepare_test_environment.sh, docker/Dockerfile.test.tmpl, docs/developer-documentation.md
- Bumps Chrome and ChromeDriver to latest stable version.
- https://chromedriver.chromium.org/downloads/version-selection
- https://developer.chrome.com/blog/chrome-for-testing/
=> Fixes the CI unit test pipeline

lib/github.py
* Adding exception-handling will prevent the server and viewer containers from crashing.
=> Adds exception handling when making an API call to Docker Hub

server.py
=> Fixes shutdown and reboot not working after a while

ansible/roles/network/tasks/main.yml, ansible/roles/screenly/files/screenly.conf, docs/balena-fleet-deployment.md, lib/utils.py, server.py
* The changes exclude references to Docker volumes
=> Renames Resin references to Balena

.github/workflows/python-lint.yaml, server.py, viewer.py
* Modified path/pattern passed to `flake8` so that root-level files like `server.py` and `viewer.py` can be included in the check.
* Fixes remaining Python linting errors in `server.py` and `viewer.py`.
=> Increases coverage of Python linter

.github/workflows/docker-test.yaml, bin/start_server.sh, docker-compose.dev.yml, server.py
* Replaced `DEVELOPMENT_MODE` with `ENVIRONMENT`
* Removed environment variables `FLASK_ENV` and `FLASK_APP`
* Specified `--debug` and `--app` in `start_server.sh` instead.
=> Refactors server scripts for development mode

lib/github.py, viewer.py
* Fixes #1964 
* Modifies `is_up_to_date` so that it will fail gracefully.
=> Fix: Making Anthias work without Internet

docker-compose.yml.tmpl, server.py, templates/settings.html
=> Fixes upgrade instructions in Settings page

webview/Dockerfile, webview/README.md, webview/build_qt5.sh, webview/src/main.cpp
=> Upgrades webview builder from Buster to Bookworm

.github/workflows/docker-build.yaml, bin/build_containers.sh
* Modifies script so that `Dockerfile.test` would not be built and pushed
=> Fixes Pi 1 builds in CI

.github/workflows/build-webview.yaml
* Enable TTY in the webview CI workflow
* #1983
=> Fixes the CI workflow for building webview binaries

bin/build_containers.sh, lib/media_player.py
* Fixes #1993
* VLC replaced OMXPlayer in #1980.
=> Cleans up unused OMX code

.github/workflows/docker-build.yaml, bin/build_containers.sh
* Updates the WebView Git hash and tag
* Removed `build_containers.sh` from the files to be ignored in the build workflow.
=> Updates WebView Git hash and tag to point to the latest version.

anthias_django/settings.py
* Brought back `localhost` and `127.0.0.1` in `ALLOWED_HOSTS`.
=> Fixes broken unit tests

.github/workflows/docker-build.yaml, README.md, bin/install.sh
* Added docs on how to opt for experimental features
* Fixed minor grammatical error(s) in the installer
=> Edits docs to include experimental features

ansible/roles/system/tasks/main.yml
* Fixes #1995
* Video tearing/flickering seems to have disappeared for Raspberry Pi devices running Raspberry Pi OS Lite.
=> Enables KMS for Raspberry Pi devices running Raspberry Pi OS Lite

server.py, tests/settings_test.py, tests/splinter_test.py
=> Adds error-handling when getting IP addresses from within the settings page

lib/utils.py
* Disabled polling from the Redis store (for IP addresses) for `development` mode.
=> Fixes server taking a while to start in a local development environment

.flake8, celery_tasks.py, host_agent.py, lib/assets_helper.py, lib/auth.py, lib/backup_helper.py, lib/github.py, lib/media_player.py, lib/queries.py, lib/utils.py, send_zmq_message.py, server.py, settings.py, tests/backup_helper_test.py, tests/celery_tasks_test.py, tests/request_test.py, tests/scheduler_test.py, tests/server_test.py, tests/settings_test.py, tests/splinter_test.py, tests/updates_test.py, tests/utils_test.py, tests/viewer_test.py, tools/migrate-assets-to-screenly.py, viewer.py
* See https://www.flake8rules.com/rules/E501.html for details.
=> Enables Flake8 E501

bin/add_certificate.sh, docker/Dockerfile.viewer.tmpl, docs/README.md
=> Creates a script for installing (trusted) self-signed certificates

celery_tasks.py, requirements/requirements.txt, requirements/requirements.viewer.txt, viewer.py
=> Replace `retry` with `tenacity`

bin/prepare_test_environment.sh, bin/start_server.sh, bin/start_viewer.sh, bin/start_wifi_connect.sh, docker/Dockerfile.base.tmpl, docker/Dockerfile.viewer.tmpl, docker/Dockerfile.websocket.tmpl
* Replaced references to `python3` to `python`.
=> Install `python-is-python3` so that `python` will point to `python3`

webview/ScreenlyWebview.pro, webview/src/main.cpp, webview/src/mainwindow.cpp, webview/src/view.cpp, webview/src/view.h
* I encountered various compilation errors when I'm trying to add support for x86, which will use Qt 6. (See #2056 for details).
* I applied the same changes here, and got no compilation errors on Pi 4 (at least). Testing to see if compilation works on Pi 1, Pi 2, and Pi 3 is still in progress.
* The changes in this PR are backward compatible with Qt 5.
=> chore: update deprecated Qt code

docs/balena-fleet-deployment.md
* Changed `dtoverlay` value from `vc4-fkms-v3d` to `vc4-kms-v3d`.
* Add an instruction for disabling overscan.
=> Update Balena deployment docs to include proper configuration values.

README.md, server.py, templates/system-info.html
* Updated `README.md` and replaced *Bullseye* with *Bookworm* for **_x86_**
* Renamed **_Raspberry Pi Model_** to **_Device Model_** in the **_System Info_** page.
=> Apply minor changes for x86

anthias_django/settings.py, bin/start_server.sh, requirements/requirements.txt, requirements/requirements.viewer.txt
* Basic filesystem manipulation to create and restore backups will be replaced by `django-dbbackup`.
* https://github.com/jazzband/django-dbbackup
=> Fix migration atomicity by using `django-dbbackup` to backup and restore database

bin/build_containers.sh, bin/deploy_to_balena.sh, docs/developer-documentation.md
* Running Anthias in development mode is not clearly documented, thus creating this pull request.
=> Update docs and scripts for setting up Anthias in development mode

bin/start_development_server.sh, docs/developer-documentation.md
* Running a few commands can be quite cumbersome, especially those that requires non-default options.
=> chore(tools): write a script for starting the development server

README.md, docs/README.md
* Added details about installing Anthias via Balena-based images
* Updated details about accessing the API docs
=> Update the documentation about using the BalenaOS images.

website/index.html
* Include x86 as one of the supported platforms.
=> Update compatibility-related info in the official website

tools/image_builder/__main__.py
* https://github.com/Screenly/Anthias/actions/runs/11726781929
=> Fix x86 docker image builds

docker/Dockerfile.server.j2
* https://github.com/Screenly/Anthias/actions/runs/11753847270/job/32747263446
=> fix: failing x86 build

.gitignore, docker/Dockerfile.server.j2, static/spec/runner.html, templates/head.html, templates/hotspot.html, templates/index.html, templates/settings.html, templates/splash-page.html, webpack.common.js
* By placing all Webpack-generated files in one directory, JS/CSS files will be easier to manage.
=> chore(workflow): place Webpack-generated static files in `./static/dist`

.github/workflows/ansible-lint.yaml, .github/workflows/build-balena-disk-image.yaml, .github/workflows/build-webview.yaml, .github/workflows/codeql-analysis.yaml, .github/workflows/deploy-website.yaml, .github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml, .github/workflows/python-lint.yaml
* https://github.com/actions/checkout/blob/main/README.md#checkout-v4
* https://github.com/actions/checkout/blob/main/CHANGELOG.md#v400
=> chore(ci): bump `actions/checkout` to `v4`

.github/workflows/deploy-website.yaml, .github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml, .github/workflows/python-lint.yaml
* https://github.com/actions/setup-python/releases/tag/v5.0.0
=> chore(ci): bump `action/setup-python` to `v5`

webview/README.md, webview/docker-compose.pi5.yml, webview/docker/Dockerfile.pi5, webview/docs/build_webview_for_pi5.md, webview/scripts/build_pi5_webview.sh
* Created scripts so that WebView can be built in a Pi 5 (for Pi 5) via the pre-build Qt 6 binaries & libraries
=> feat: write scripts for building a Pi 5 WebView

.github/workflows/docker-build.yaml
Fixes the issue in the following CI run: https://github.com/Screenly/Anthias/actions/runs/12427404374
=> fix: syntax errors in `docker-build.yaml`

README.md, website/index.html
* Adds a quick link to the WebView documentation from `README.md`
=> docs: add more details about WebView and Pi 5 compatibility

docs/installation-options.md
This pull request updates the documentation to include support for balenaOS on Raspberry Pi 5 devices.
=> docs: update docs to include balenaOS support for Pi 5

docs/installation-options.md
Now that Anthias supports Raspberry Pi 5 (via the release images), we should update the documentation.
=> docs: update info about Pi 5 compatibility

.github/workflows/javascript-lint.yaml, .gitignore, coffeelint.json, eslint.config.mjs, package-lock.json, package.json, static/js/anthias.coffee, static/js/settings.coffee, webpack.common.js, webpack.dev.js, webpack.prod.js
Adds a pipeline for linting JavaScript and CoffeeScript files.
=> chore: add a pipeline for linting JS and CoffeeScript files

.github/ISSUE_TEMPLATE/dependency_upgrade.md
Created an issue template related to updating dependencies (e.g., upgrading from Django 4 to 5, migrating from CoffeeScript to TypeScript, etc.)
=> chore: create an issue template related to updating dependencies

.github/workflows/build-webview.yaml, .github/workflows/generate-openapi-schema.yml
=> Revert "chore(ci): bump `actions/upload-artifact` to `v4`"

tools/image_builder/__main__.py, tools/image_builder/utils.py
=> Revert "fix: set target platform of Pi 4 images to `linux/arm64/v8`"

.github/workflows/sbom.yaml
Adds a workflow call to `run-tests`.
=> chore(ci): fix SBOM workflow issues

website/index.html
Updates the website's copyright year
=> chore: update website's copyright year

.github/workflows/lint-workflows.yml
Refactored `lint-workflows.yml` so that a fixed version of `actionlint` is used
=> chore(ci): update and refactor the workflow linter pipeline

tools/image_builder/utils.py
* Fixes #2219
* Updates the WebView version used so that [WebView-v0.3.5](https://github.com/Screenly/Anthias/releases/tag/WebView-v0.3.5) will be used
=> fix: update WebView Git hashes

docs/raspberry-pi5-ssd-install-instructions.md
Created guide to booting a Pi5 from a NVMe SSD and installing Anthias on it.
Pretty self explanatory guide, tested on my local system and works fine.
=> Added instructions on booting Pi5 from NVMe SSD

docs/installation-options.md
Include a list of issues that this pull request fixes. If this pull request is not associated with any issue, you can remove this section or include a brief description of the issue that you are fixing.
Provide a brief description of the changes that you have made.
Include any additional information that you think is necessary for this pull request, including screenshots of the changes that you have made.
=> Update for installation instructions to link to Pi5/SSD docs.

.github/workflows/build-webview.yaml, webview/build_webview_with_qt5.sh
Include a list of issues that this pull request fixes. If this pull request is not associated with any issue, you can remove this section or include a brief description of the issue that you are fixing.
Provide a brief description of the changes that you have made.
Include any additional information that you think is necessary for this pull request, including screenshots of the changes that you have made.
=> chore(ci): fix the workflow for building WebView binaries

.github/workflows/build-webview.yaml
*  Fixes issues with creating the release and finding files
=> chore(ci): fix issues with creating the release and finding files

docker/Dockerfile.viewer.j2, tools/image_builder/utils.py
* Fixes #2229
Yellow outline appears around the first IP address on the splash screen
=> fix: use `WebView-v0.3.6`

.editorconfig, .github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml, .github/workflows/generate-openapi-schema.yml
- Creates an `.editorconfig` file so that formatting guidelines will be consistent, especially the indentation.
=> chore: create an `.editorconfig` file

tools/image_builder/utils.py
- Fixes #2051
- Updated WebView version used by Anthias to `v0.3.7`.
=> fix: update WebView version and hash

api/serializers/v2.py, api/tests/__init__.py, api/tests/test_assets.py, api/tests/test_common.py, api/tests/test_v1_endpoints.py, api/tests/test_v2_endpoints.py, api/urls/v2.py, api/views/v2.py
Write an endpoint for showing device settings.
=> feat: write endpoint for device settings

api/tests/test_info_endpoints.py, api/tests/test_v1_endpoints.py, api/urls/v2.py, api/views/mixins.py, api/views/v1.py, api/views/v2.py
- Adds a new v2 endpoint for showing the system info
=> feat: add a new V2 endpoint for showing system info

.github/workflows/docker-build.yaml
- It's taking a while for the Docker image builds to finish.
- Updated Docker build pipeline to support building for each services in parallel
=> chore(ci): update docker build pipeline to support building for each services in parallel

.cursor/rules/general.mdc, .cursor/rules/javascript.mdc, .cursor/rules/python.mdc, .cursor/rules/qt.mdc, .github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml, .github/workflows/generate-openapi-schema.yml
- Created a `.cursor/rules` directory, which containes several `.mdc` files.
=> chore: create Cursor rules

.github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml, .github/workflows/generate-openapi-schema.yml, CONTRIBUTING.md
- Created a document for contributing guidelines
=> chore(ci): create a `CONTRIBUTING.md` file

website/index.html
- Fixes broken link in the following FAQ sub-sections:
- "What is the difference between Anthias and Screenly"
- "Is there support for Anthias?"
=> fix: broken links in the Anthias website

api/serializers/v2.py, api/tests/test_v2_endpoints.py, api/urls/v2.py, api/views/v2.py
=> Revert "api: write new endpoint for info about the Balena integration"

api/serializers/v2.py, api/tests/test_v2_endpoints.py, api/urls/v2.py, api/views/v2.py
=> Revert "Revert "api: write new endpoint for info about the Balena integration""

api/serializers/v2.py, api/tests/test_v2_endpoints.py, api/views/v2.py
- Created a new endpoint `PATCH /api/v2/device_settings` for updating the settings
=> api: new endpoint for updating device settings

api/serializers/v2.py, api/tests/test_v2_endpoints.py, api/views/v2.py
- Updated `PATCH /api/v2/device_settings`
=> api: update `PATCH /api/v2/device_settings` to handle auth

.cursor/rules/css.mdc
- Created Cursor rules for SCSS/CSS
=> chore: create a new set of Cursor rules for SCSS/CSS files

.github/release.yml
Fixes syntax error in `.github/release.yml`
=> chore(ci): fix release.yml

.github/workflows/build-balena-disk-image.yaml
=> Revert "fix: replace `zip` with `xz` for compression"

static/src/components/settings.jsx
Code duplication in `settings.jsx`&mdash;`handleReboot` and `handleShutdown` duplicate each other.
Refactors `handleReboot` and `handleShutdown`
=> chore: refactor handling of reboot and shutdown via web UI

static/sass/_styles.scss, static/sass/_variables.scss, static/src/components/asset-modal/uri-tab.jsx, static/src/components/edit-asset-modal.jsx, static/src/components/settings.jsx
- Changed the border color of form inputs from a shade of yellow to a shade or purple when focused
- Removed the box shadows from form inputs
=> feat: change focus color of inputs to a shade of purple

static/src/store/index.js, webpack.dev.js, webpack.prod.js
=> Revert "chore: disable Redux DevTools in production"

static/src/components/empty-asset-message.jsx
- https://github.com/Screenly/Anthias/actions/runs/15690513144
Applied JavaScript formatting fixes using Prettier.
=> chore(ci): fix JavaScript formatting issues

static/sass/_styles.scss, static/sass/_tooltip.scss, static/src/components/asset-row/utils.js, static/src/components/home.jsx
- Changed the background color, foreground color, and transition duration of tooltips so that the styling will be consistent
- Moved tooltip styles from the JSX file to a SCSS file
=> feat: re-style the tooltips

static/sass/_styles.scss, static/sass/_sweetalert2-overrides.scss, static/src/components/asset-row/index.jsx, static/src/components/asset-row/utils.js, static/src/components/settings/backup.jsx, static/src/components/settings/index.jsx, static/src/components/settings/system-controls.jsx
- Changed the background and foreground colors of the buttons to make them consistent with the rest of the components
=> feat: restyle alerts

static/sass/_styles.scss, static/src/components/active-assets.jsx, static/src/components/inactive-assets.jsx
- Aligned table headers to center
- Added a label to the rightmost table header&mdash;"Actions"
=> feat: restyle active and inactive assets components

.github/workflows/docker-build.yaml
Temporary changes to #2351 was not reverted before the PR was merged. This PR fixes the issue.
=> chore(ci): re-enable build workflow on push to `master`

.github/workflows/docker-test.yaml
Refactors `docker-test.yml` to sort out code duplication
=> chore(ci): refactor test workflow

.github/workflows/generate-openapi-schema.yml
Refactors `generate-openapi-schema.yml` to sort out code duplication
=> chore(ci): refactor OpenAPI schema generation workflow

static/src/components/settings/index.tsx
- Removed the Cancel button from the Settings page
- Clicking the Cancel button will only redirect users to the home page.
=> feat: remove Cancel button from Settings page

webview/src/mainwindow.cpp, webview/src/mainwindow.h, webview/src/view.cpp, webview/src/view.h
Adds support for controlling web assets' zoom level in WebView
=> feat: add WebView support for zoom level in web pages

CONTRIBUTING.md
Updates `CONTRIBUTING.md` so that how the `tests` label should be used is included in it.
=> docs: include using the `tests` label in `CONTRIBUTING.md`

.github/workflows/docker-build.yaml, .github/workflows/docker-test.yaml
- Updates `docker-test.yml` to ignore `.editorconfig` and `CONTRIBUTING.md` when the workflow is triggered by an opened PR
- Updates `docker-build.yml` to ignore changes to `docker-test.yml`
=> chore: update test workflow to ignore files when workflow is triggered by PR creation

webview/src/view.cpp, webview/src/view.h
=> fix: WebView support for GIF assets

tools/image_builder/utils.py
=> fix: update WebView hash to support GIFs

static/src/components/active-assets.tsx, static/src/components/asset-row/index.tsx, static/src/components/home.tsx, static/src/components/inactive-assets.tsx, static/src/components/navbar.tsx
- The navigation bar in the web UI isn't responsive in displays with smaller widths.
- Made use of Bootstrap 5's navbar utilities to make the component responsive
=> fix: make the web UI more responsive
